/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.111.19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddWorkflowStepRelationshipResponse {
    /// Steps that cannot be reached from Link Visit now that this connection exists, reported without being asked for.  Rewiring a workflow detaches things: links_create seeds an exit redirect, and the moment the entry routes through a condition instead, that redirect is stranded. It happened on a real link, which shipped with a floating redirect the builder never mentioned, because noticing depended on remembering to run a separate validation call. The server knows at the moment it happens, so it says so here. Empty means everything is connected.
    #[serde(rename = "disconnectedSteps", skip_serializing_if = "Option::is_none")]
    pub disconnected_steps: Option<Vec<models::WorkflowIssue>>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl AddWorkflowStepRelationshipResponse {
    pub fn new() -> AddWorkflowStepRelationshipResponse {
        AddWorkflowStepRelationshipResponse {
            disconnected_steps: None,
            message: None,
        }
    }
}

