/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.108.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentSendMessageRequest {
    #[serde(rename = "contextId", skip_serializing_if = "Option::is_none")]
    pub context_id: Option<String>,
    #[serde(rename = "contextMetadata", skip_serializing_if = "Option::is_none")]
    pub context_metadata: Option<String>,
    #[serde(rename = "contextType", skip_serializing_if = "Option::is_none")]
    pub context_type: Option<models::AgentContextType>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl AgentSendMessageRequest {
    pub fn new() -> AgentSendMessageRequest {
        AgentSendMessageRequest {
            context_id: None,
            context_metadata: None,
            context_type: None,
            message: None,
        }
    }
}

