/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.121.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentGetConversationResponse {
    #[serde(rename = "messages", skip_serializing_if = "Option::is_none")]
    pub messages: Option<Vec<models::AgentDisplayMessage>>,
    /// Assistant messages in this conversation the member has not seen yet.
    #[serde(rename = "unreadCount", skip_serializing_if = "Option::is_none")]
    pub unread_count: Option<i32>,
}

impl AgentGetConversationResponse {
    pub fn new() -> AgentGetConversationResponse {
        AgentGetConversationResponse {
            messages: None,
            unread_count: None,
        }
    }
}

