/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.87.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AiContextType {
    #[serde(rename = "AI_CONTEXT_TYPE_UNSPECIFIED")]
    AiContextTypeUnspecified,
    #[serde(rename = "AI_CONTEXT_TYPE_ANALYTICS_DASHBOARD")]
    AiContextTypeAnalyticsDashboard,
    #[serde(rename = "AI_CONTEXT_TYPE_WORKFLOW")]
    AiContextTypeWorkflow,
    #[serde(rename = "AI_CONTEXT_TYPE_LINK")]
    AiContextTypeLink,
    #[serde(rename = "AI_CONTEXT_TYPE_QRCODE_DESIGN")]
    AiContextTypeQrcodeDesign,
    #[serde(rename = "AI_CONTEXT_TYPE_PAGE_THEME")]
    AiContextTypePageTheme,

}

impl std::fmt::Display for AiContextType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AiContextTypeUnspecified => write!(f, "AI_CONTEXT_TYPE_UNSPECIFIED"),
            Self::AiContextTypeAnalyticsDashboard => write!(f, "AI_CONTEXT_TYPE_ANALYTICS_DASHBOARD"),
            Self::AiContextTypeWorkflow => write!(f, "AI_CONTEXT_TYPE_WORKFLOW"),
            Self::AiContextTypeLink => write!(f, "AI_CONTEXT_TYPE_LINK"),
            Self::AiContextTypeQrcodeDesign => write!(f, "AI_CONTEXT_TYPE_QRCODE_DESIGN"),
            Self::AiContextTypePageTheme => write!(f, "AI_CONTEXT_TYPE_PAGE_THEME"),
        }
    }
}

impl Default for AiContextType {
    fn default() -> AiContextType {
        Self::AiContextTypeUnspecified
    }
}

