/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.126.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplyPageThemeTemplateRequest {
    #[serde(rename = "linkId")]
    pub link_id: String,
    /// Template to apply, addressed by ID. Use this for workspace templates that have not been published and therefore have no slug.
    #[serde(rename = "pageThemeTemplateId", skip_serializing_if = "Option::is_none")]
    pub page_theme_template_id: Option<String>,
    /// Slug of the page theme template to apply.  Only published and built-in templates carry a slug: it is the public identifier the gallery and the marketing site address them by. Supply page_theme_template_id instead for a workspace's own drafts, which have none. Exactly one of the two is required.
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
}

impl ApplyPageThemeTemplateRequest {
    pub fn new(link_id: String) -> ApplyPageThemeTemplateRequest {
        ApplyPageThemeTemplateRequest {
            link_id,
            page_theme_template_id: None,
            slug: None,
        }
    }
}

