/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.134.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssistantMarkConversationReadResponse {
    #[serde(rename = "markedCount", skip_serializing_if = "Option::is_none")]
    pub marked_count: Option<i32>,
}

impl AssistantMarkConversationReadResponse {
    pub fn new() -> AssistantMarkConversationReadResponse {
        AssistantMarkConversationReadResponse {
            marked_count: None,
        }
    }
}

