/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.119.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AutoLayoutWorkflowResponse {
    #[serde(rename = "stepsRepositioned", skip_serializing_if = "Option::is_none")]
    pub steps_repositioned: Option<i32>,
}

impl AutoLayoutWorkflowResponse {
    pub fn new() -> AutoLayoutWorkflowResponse {
        AutoLayoutWorkflowResponse {
            steps_repositioned: None,
        }
    }
}

