/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BackgroundOptions {
    #[serde(rename = "themeColor", skip_serializing_if = "Option::is_none")]
    pub theme_color: Option<Box<models::ThemeColor>>,
}

impl BackgroundOptions {
    pub fn new() -> BackgroundOptions {
        BackgroundOptions {
            theme_color: None,
        }
    }
}

