/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.148.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BillingInterval : - BILLING_INTERVAL_UNSPECIFIED: Not set  - BILLING_INTERVAL_MONTH: Charged every month  - BILLING_INTERVAL_YEAR: Charged every year  - BILLING_INTERVAL_ONE_TIME: Charged once
/// - BILLING_INTERVAL_UNSPECIFIED: Not set  - BILLING_INTERVAL_MONTH: Charged every month  - BILLING_INTERVAL_YEAR: Charged every year  - BILLING_INTERVAL_ONE_TIME: Charged once
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BillingInterval {
    #[serde(rename = "BILLING_INTERVAL_UNSPECIFIED")]
    BillingIntervalUnspecified,
    #[serde(rename = "BILLING_INTERVAL_MONTH")]
    BillingIntervalMonth,
    #[serde(rename = "BILLING_INTERVAL_YEAR")]
    BillingIntervalYear,
    #[serde(rename = "BILLING_INTERVAL_ONE_TIME")]
    BillingIntervalOneTime,

}

impl std::fmt::Display for BillingInterval {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::BillingIntervalUnspecified => write!(f, "BILLING_INTERVAL_UNSPECIFIED"),
            Self::BillingIntervalMonth => write!(f, "BILLING_INTERVAL_MONTH"),
            Self::BillingIntervalYear => write!(f, "BILLING_INTERVAL_YEAR"),
            Self::BillingIntervalOneTime => write!(f, "BILLING_INTERVAL_ONE_TIME"),
        }
    }
}

impl Default for BillingInterval {
    fn default() -> BillingInterval {
        Self::BillingIntervalUnspecified
    }
}

