/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.95.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompleteGoogleFormsOAuthResponse {
    #[serde(rename = "integration", skip_serializing_if = "Option::is_none")]
    pub integration: Option<Box<models::GoogleFormsIntegration>>,
}

impl CompleteGoogleFormsOAuthResponse {
    pub fn new() -> CompleteGoogleFormsOAuthResponse {
        CompleteGoogleFormsOAuthResponse {
            integration: None,
        }
    }
}

