/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.111.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompleteSlackOAuthResponse {
    #[serde(rename = "slackIntegration", skip_serializing_if = "Option::is_none")]
    pub slack_integration: Option<Box<models::SlackIntegration>>,
}

impl CompleteSlackOAuthResponse {
    pub fn new() -> CompleteSlackOAuthResponse {
        CompleteSlackOAuthResponse {
            slack_integration: None,
        }
    }
}

