/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContactCardTraceData : ContactCardTraceData stores contact card engagement details.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContactCardTraceData {
    #[serde(rename = "card", skip_serializing_if = "Option::is_none")]
    pub card: Option<Box<models::ContactCardTraceCard>>,
}

impl ContactCardTraceData {
    /// ContactCardTraceData stores contact card engagement details.
    pub fn new() -> ContactCardTraceData {
        ContactCardTraceData {
            card: None,
        }
    }
}

