/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.77.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CornersSquareType {
    #[serde(rename = "CORNERS_SQUARE_TYPE_UNSPECIFIED")]
    CornersSquareTypeUnspecified,
    #[serde(rename = "CORNERS_SQUARE_TYPE_DOT")]
    CornersSquareTypeDot,
    #[serde(rename = "CORNERS_SQUARE_TYPE_SQUARE")]
    CornersSquareTypeSquare,
    #[serde(rename = "CORNERS_SQUARE_TYPE_EXTRA_ROUNDED")]
    CornersSquareTypeExtraRounded,
    #[serde(rename = "CORNERS_SQUARE_TYPE_HEXAGON")]
    CornersSquareTypeHexagon,
    #[serde(rename = "CORNERS_SQUARE_TYPE_OCTAGON")]
    CornersSquareTypeOctagon,
    #[serde(rename = "CORNERS_SQUARE_TYPE_LEAF")]
    CornersSquareTypeLeaf,

}

impl std::fmt::Display for CornersSquareType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CornersSquareTypeUnspecified => write!(f, "CORNERS_SQUARE_TYPE_UNSPECIFIED"),
            Self::CornersSquareTypeDot => write!(f, "CORNERS_SQUARE_TYPE_DOT"),
            Self::CornersSquareTypeSquare => write!(f, "CORNERS_SQUARE_TYPE_SQUARE"),
            Self::CornersSquareTypeExtraRounded => write!(f, "CORNERS_SQUARE_TYPE_EXTRA_ROUNDED"),
            Self::CornersSquareTypeHexagon => write!(f, "CORNERS_SQUARE_TYPE_HEXAGON"),
            Self::CornersSquareTypeOctagon => write!(f, "CORNERS_SQUARE_TYPE_OCTAGON"),
            Self::CornersSquareTypeLeaf => write!(f, "CORNERS_SQUARE_TYPE_LEAF"),
        }
    }
}

impl Default for CornersSquareType {
    fn default() -> CornersSquareType {
        Self::CornersSquareTypeUnspecified
    }
}

