/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.107.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CornersDotType {
    #[serde(rename = "CORNERS_DOT_TYPE_UNSPECIFIED")]
    CornersDotTypeUnspecified,
    #[serde(rename = "CORNERS_DOT_TYPE_DOT")]
    CornersDotTypeDot,
    #[serde(rename = "CORNERS_DOT_TYPE_SQUARE")]
    CornersDotTypeSquare,
    #[serde(rename = "CORNERS_DOT_TYPE_HEXAGON")]
    CornersDotTypeHexagon,
    #[serde(rename = "CORNERS_DOT_TYPE_OCTAGON")]
    CornersDotTypeOctagon,
    #[serde(rename = "CORNERS_DOT_TYPE_TEARDROP")]
    CornersDotTypeTeardrop,
    #[serde(rename = "CORNERS_DOT_TYPE_STAR")]
    CornersDotTypeStar,

}

impl std::fmt::Display for CornersDotType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CornersDotTypeUnspecified => write!(f, "CORNERS_DOT_TYPE_UNSPECIFIED"),
            Self::CornersDotTypeDot => write!(f, "CORNERS_DOT_TYPE_DOT"),
            Self::CornersDotTypeSquare => write!(f, "CORNERS_DOT_TYPE_SQUARE"),
            Self::CornersDotTypeHexagon => write!(f, "CORNERS_DOT_TYPE_HEXAGON"),
            Self::CornersDotTypeOctagon => write!(f, "CORNERS_DOT_TYPE_OCTAGON"),
            Self::CornersDotTypeTeardrop => write!(f, "CORNERS_DOT_TYPE_TEARDROP"),
            Self::CornersDotTypeStar => write!(f, "CORNERS_DOT_TYPE_STAR"),
        }
    }
}

impl Default for CornersDotType {
    fn default() -> CornersDotType {
        Self::CornersDotTypeUnspecified
    }
}

