/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.13
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CornersDotOptions {
    #[serde(rename = "themeColor", skip_serializing_if = "Option::is_none")]
    pub theme_color: Option<Box<models::ThemeColor>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl CornersDotOptions {
    pub fn new() -> CornersDotOptions {
        CornersDotOptions {
            theme_color: None,
            r#type: None,
        }
    }
}

