/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.45.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CountryConditionOutcome {
    #[serde(rename = "countryCode", skip_serializing_if = "Option::is_none")]
    pub country_code: Option<String>,
    #[serde(rename = "nextStepId", skip_serializing_if = "Option::is_none")]
    pub next_step_id: Option<String>,
}

impl CountryConditionOutcome {
    pub fn new() -> CountryConditionOutcome {
        CountryConditionOutcome {
            country_code: None,
            next_step_id: None,
        }
    }
}

