/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.121.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateDashboardRequest {
    /// Initial widgets. Empty means the dashboard starts with none, because its contents are normally agreed with the agent before anything is created.
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<Box<models::DashboardConfig>>,
    /// Client-supplied dashboard id. Generated server-side when empty.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Link to scope this dashboard to. Empty creates the workspace-wide dashboard.
    #[serde(rename = "linkId", skip_serializing_if = "Option::is_none")]
    pub link_id: Option<String>,
    /// Display name. Defaults to \"Default Dashboard\" when empty.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Fill a workspace dashboard with the standard starter widgets instead of leaving it empty. For the first dashboard in a workspace, which is created by one click rather than by a conversation. Ignored when config is set or when link_id is set, and hidden from the agent, which agrees its widgets with the user and would otherwise stack them on top of these.
    #[serde(rename = "useDefaultWidgets", skip_serializing_if = "Option::is_none")]
    pub use_default_widgets: Option<bool>,
}

impl CreateDashboardRequest {
    pub fn new() -> CreateDashboardRequest {
        CreateDashboardRequest {
            config: None,
            id: None,
            link_id: None,
            name: None,
            use_default_widgets: None,
        }
    }
}

