/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.125.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreatePageThemeTemplateRequest : CreatePageThemeTemplateRequest represents a request to create a new page theme template.  The template's styling is copied from an existing page theme, which is normally a link's theme the user wants to reuse. The copy is detached, so editing the link afterwards does not change the template.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePageThemeTemplateRequest {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "faq", skip_serializing_if = "Option::is_none")]
    pub faq: Option<String>,
    #[serde(rename = "learnMore", skip_serializing_if = "Option::is_none")]
    pub learn_more: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Page theme to copy the styling from, usually a link's own theme. Omit to start from the default styling.
    #[serde(rename = "sourcePageThemeId", skip_serializing_if = "Option::is_none")]
    pub source_page_theme_id: Option<String>,
    /// Styling to capture, taking precedence over source_page_theme_id.  The editor sends what is on screen, so saving a theme as a template records the look the user is actually looking at rather than the last saved one.
    #[serde(rename = "styling", skip_serializing_if = "Option::is_none")]
    pub styling: Option<Box<models::PageThemeStyling>>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<String>,
}

impl CreatePageThemeTemplateRequest {
    /// CreatePageThemeTemplateRequest represents a request to create a new page theme template.  The template's styling is copied from an existing page theme, which is normally a link's theme the user wants to reuse. The copy is detached, so editing the link afterwards does not change the template.
    pub fn new() -> CreatePageThemeTemplateRequest {
        CreatePageThemeTemplateRequest {
            description: None,
            faq: None,
            learn_more: None,
            name: None,
            source_page_theme_id: None,
            styling: None,
            tags: None,
        }
    }
}

