/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.146.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateWorkspaceTokenRequest {
    #[serde(rename = "keyType")]
    pub key_type: models::WorkspaceTokenKeyType,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The scopes the token may use. Leave empty for full access. A write scope also grants the read scope of the same resource. Publishable keys take no scopes. A token can only grant scopes it holds itself.
    #[serde(rename = "scopes", skip_serializing_if = "Option::is_none")]
    pub scopes: Option<Vec<models::ApiScope>>,
}

impl CreateWorkspaceTokenRequest {
    pub fn new(key_type: models::WorkspaceTokenKeyType) -> CreateWorkspaceTokenRequest {
        CreateWorkspaceTokenRequest {
            key_type,
            name: None,
            scopes: None,
        }
    }
}

