/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.106.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateLinkResponse {
    #[serde(rename = "link", skip_serializing_if = "Option::is_none")]
    pub link: Option<Box<models::Link>>,
    /// The workflow steps that were created alongside the link.  Every link is created with an entry step (event_action EVENT_ACTION_LINK_VISIT, kind KIND_ENTRY) and a default exit step, already connected to each other. They are returned here so a caller never has to guess or look up the entry step's id before attaching its own steps to it.
    #[serde(rename = "workflowSteps", skip_serializing_if = "Option::is_none")]
    pub workflow_steps: Option<Vec<models::WorkflowStep>>,
}

impl CreateLinkResponse {
    pub fn new() -> CreateLinkResponse {
        CreateLinkResponse {
            link: None,
            workflow_steps: None,
        }
    }
}

