/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.43.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateBulkLinksResponse : Response containing all created links from a successful batch.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateBulkLinksResponse {
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Vec<models::Link>>,
}

impl CreateBulkLinksResponse {
    /// Response containing all created links from a successful batch.
    pub fn new() -> CreateBulkLinksResponse {
        CreateBulkLinksResponse {
            links: None,
        }
    }
}

