/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.87.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateDashboardResponse {
    #[serde(rename = "dashboard", skip_serializing_if = "Option::is_none")]
    pub dashboard: Option<Box<models::AnalyticsDashboard>>,
}

impl CreateDashboardResponse {
    pub fn new() -> CreateDashboardResponse {
        CreateDashboardResponse {
            dashboard: None,
        }
    }
}

