/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateDirectoryRequest {
    /// The name of the directory. This field is required.
    #[serde(rename = "name")]
    pub name: String,
    /// The ID of the parent directory (UUID) If not provided, the directory will be created at the root level.
    #[serde(rename = "parentDirectoryId", skip_serializing_if = "Option::is_none")]
    pub parent_directory_id: Option<String>,
}

impl CreateDirectoryRequest {
    pub fn new(name: String) -> CreateDirectoryRequest {
        CreateDirectoryRequest {
            name,
            parent_directory_id: None,
        }
    }
}

