/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.13
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCustomDomainResponse {
    #[serde(rename = "customDomain", skip_serializing_if = "Option::is_none")]
    pub custom_domain: Option<Box<models::CustomDomain>>,
}

impl CreateCustomDomainResponse {
    pub fn new() -> CreateCustomDomainResponse {
        CreateCustomDomainResponse {
            custom_domain: None,
        }
    }
}

