/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateMediaRequest {
    /// The file data to upload. The file size limit is 3MB. It must be transmitted in a base64 string format when sending it through HTTP. Accepted formats are PNG and JPEG.
    #[serde(rename = "fileData", skip_serializing_if = "Option::is_none")]
    pub file_data: Option<String>,
    #[serde(rename = "fileName", skip_serializing_if = "Option::is_none")]
    pub file_name: Option<String>,
    /// Supports CENTRAL_QRCODE_IMAGE, BACKGROUND_COVER, and BADGE
    #[serde(rename = "mediaType", skip_serializing_if = "Option::is_none")]
    pub media_type: Option<models::MediaType>,
    /// The visibility of the media.  If not provided, the media file will be private.
    #[serde(rename = "visibility", skip_serializing_if = "Option::is_none")]
    pub visibility: Option<models::MediaVisibility>,
}

impl CreateMediaRequest {
    pub fn new() -> CreateMediaRequest {
        CreateMediaRequest {
            file_data: None,
            file_name: None,
            media_type: None,
            visibility: None,
        }
    }
}

