/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.146.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreditTopup {
    #[serde(rename = "amounts", skip_serializing_if = "Option::is_none")]
    pub amounts: Option<Vec<models::Money>>,
    #[serde(rename = "creditsPerUnit", skip_serializing_if = "Option::is_none")]
    pub credits_per_unit: Option<i32>,
}

impl CreditTopup {
    pub fn new() -> CreditTopup {
        CreditTopup {
            amounts: None,
            credits_per_unit: None,
        }
    }
}

