/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.148.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomDomainDnsRecord {
    #[serde(rename = "detected", skip_serializing_if = "Option::is_none")]
    pub detected: Option<bool>,
    /// What to type in the provider's host field: the name relative to the zone, e.g. \"qr\". For the zone apex, \"@\", or empty when the provider wants the field left blank.
    #[serde(rename = "host", skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "purpose", skip_serializing_if = "Option::is_none")]
    pub purpose: Option<models::DnsRecordPurpose>,
    /// Whether setup is incomplete without it. The routing record and the certificate delegation record (which keeps HTTPS renewing on its own) are both required.
    #[serde(rename = "required", skip_serializing_if = "Option::is_none")]
    pub required: Option<bool>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::DnsRecordType>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl CustomDomainDnsRecord {
    pub fn new() -> CustomDomainDnsRecord {
        CustomDomainDnsRecord {
            detected: None,
            host: None,
            name: None,
            purpose: None,
            required: None,
            r#type: None,
            value: None,
        }
    }
}

