/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.112.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DashboardConfig {
    /// Width of the grid the widget positions and sizes are expressed in. Absent or 0 means the legacy two-column grid, where w=1 is half-width and w=2 is full-width. New dashboards use 8.
    #[serde(rename = "gridColumns", skip_serializing_if = "Option::is_none")]
    pub grid_columns: Option<i32>,
    #[serde(rename = "widgets", skip_serializing_if = "Option::is_none")]
    pub widgets: Option<Vec<models::DashboardWidget>>,
}

impl DashboardConfig {
    pub fn new() -> DashboardConfig {
        DashboardConfig {
            grid_columns: None,
            widgets: None,
        }
    }
}

