/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.110.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DashboardScope : DashboardScope selects dashboards by whether they are tied to a link.   - DASHBOARD_SCOPE_UNSPECIFIED: Every dashboard in the workspace, link-scoped or not.  - DASHBOARD_SCOPE_WORKSPACE: Only the workspace-wide dashboard, the one with no link.  - DASHBOARD_SCOPE_LINK: Only dashboards tied to a link.
/// DashboardScope selects dashboards by whether they are tied to a link.   - DASHBOARD_SCOPE_UNSPECIFIED: Every dashboard in the workspace, link-scoped or not.  - DASHBOARD_SCOPE_WORKSPACE: Only the workspace-wide dashboard, the one with no link.  - DASHBOARD_SCOPE_LINK: Only dashboards tied to a link.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DashboardScope {
    #[serde(rename = "DASHBOARD_SCOPE_UNSPECIFIED")]
    DashboardScopeUnspecified,
    #[serde(rename = "DASHBOARD_SCOPE_WORKSPACE")]
    DashboardScopeWorkspace,
    #[serde(rename = "DASHBOARD_SCOPE_LINK")]
    DashboardScopeLink,

}

impl std::fmt::Display for DashboardScope {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DashboardScopeUnspecified => write!(f, "DASHBOARD_SCOPE_UNSPECIFIED"),
            Self::DashboardScopeWorkspace => write!(f, "DASHBOARD_SCOPE_WORKSPACE"),
            Self::DashboardScopeLink => write!(f, "DASHBOARD_SCOPE_LINK"),
        }
    }
}

impl Default for DashboardScope {
    fn default() -> DashboardScope {
        Self::DashboardScopeUnspecified
    }
}

