/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.123.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeviceActorConditionOption : Device actor condition option for EVENT_ACTION_DEVICE_ACTOR_CONDITION.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceActorConditionOption {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "nextStepId", skip_serializing_if = "Option::is_none")]
    pub next_step_id: Option<String>,
    /// Allowed values for device actor routing conditions.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<Value>,
}

impl DeviceActorConditionOption {
    /// Device actor condition option for EVENT_ACTION_DEVICE_ACTOR_CONDITION.
    pub fn new() -> DeviceActorConditionOption {
        DeviceActorConditionOption {
            id: None,
            name: None,
            next_step_id: None,
            value: None,
        }
    }
}
/// Allowed values for device actor routing conditions.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Value {
    #[serde(rename = "DEVICE_ACTOR_CONDITION_VALUE_UNSPECIFIED")]
    DeviceActorConditionValueUnspecified,
    #[serde(rename = "DEVICE_ACTOR_CONDITION_VALUE_HUMAN")]
    DeviceActorConditionValueHuman,
    #[serde(rename = "DEVICE_ACTOR_CONDITION_VALUE_BOT")]
    DeviceActorConditionValueBot,
    #[serde(rename = "DEVICE_ACTOR_CONDITION_VALUE_AGENT")]
    DeviceActorConditionValueAgent,
    #[serde(rename = "DEVICE_ACTOR_CONDITION_VALUE_UNKNOWN")]
    DeviceActorConditionValueUnknown,
}

impl Default for Value {
    fn default() -> Value {
        Self::DeviceActorConditionValueUnspecified
    }
}

