/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.119.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeviceBrowserConditionOption : Device browser condition option for EVENT_ACTION_DEVICE_BROWSER_CONDITION.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceBrowserConditionOption {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "nextStepId", skip_serializing_if = "Option::is_none")]
    pub next_step_id: Option<String>,
    /// Allowed values for device browser routing conditions.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<Value>,
}

impl DeviceBrowserConditionOption {
    /// Device browser condition option for EVENT_ACTION_DEVICE_BROWSER_CONDITION.
    pub fn new() -> DeviceBrowserConditionOption {
        DeviceBrowserConditionOption {
            id: None,
            name: None,
            next_step_id: None,
            value: None,
        }
    }
}
/// Allowed values for device browser routing conditions.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Value {
    #[serde(rename = "DEVICE_BROWSER_CONDITION_VALUE_UNSPECIFIED")]
    DeviceBrowserConditionValueUnspecified,
    #[serde(rename = "DEVICE_BROWSER_CONDITION_VALUE_CHROME")]
    DeviceBrowserConditionValueChrome,
    #[serde(rename = "DEVICE_BROWSER_CONDITION_VALUE_SAFARI")]
    DeviceBrowserConditionValueSafari,
    #[serde(rename = "DEVICE_BROWSER_CONDITION_VALUE_FIREFOX")]
    DeviceBrowserConditionValueFirefox,
    #[serde(rename = "DEVICE_BROWSER_CONDITION_VALUE_EDGE")]
    DeviceBrowserConditionValueEdge,
    #[serde(rename = "DEVICE_BROWSER_CONDITION_VALUE_OPERA")]
    DeviceBrowserConditionValueOpera,
    #[serde(rename = "DEVICE_BROWSER_CONDITION_VALUE_SAMSUNG_BROWSER")]
    DeviceBrowserConditionValueSamsungBrowser,
}

impl Default for Value {
    fn default() -> Value {
        Self::DeviceBrowserConditionValueUnspecified
    }
}

