/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.44.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeviceActorConditionValue : Allowed values for device actor routing conditions.
/// Allowed values for device actor routing conditions.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeviceActorConditionValue {
    #[serde(rename = "DEVICE_ACTOR_CONDITION_VALUE_UNSPECIFIED")]
    DeviceActorConditionValueUnspecified,
    #[serde(rename = "DEVICE_ACTOR_CONDITION_VALUE_HUMAN")]
    DeviceActorConditionValueHuman,
    #[serde(rename = "DEVICE_ACTOR_CONDITION_VALUE_BOT")]
    DeviceActorConditionValueBot,
    #[serde(rename = "DEVICE_ACTOR_CONDITION_VALUE_AGENT")]
    DeviceActorConditionValueAgent,
    #[serde(rename = "DEVICE_ACTOR_CONDITION_VALUE_UNKNOWN")]
    DeviceActorConditionValueUnknown,

}

impl std::fmt::Display for DeviceActorConditionValue {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DeviceActorConditionValueUnspecified => write!(f, "DEVICE_ACTOR_CONDITION_VALUE_UNSPECIFIED"),
            Self::DeviceActorConditionValueHuman => write!(f, "DEVICE_ACTOR_CONDITION_VALUE_HUMAN"),
            Self::DeviceActorConditionValueBot => write!(f, "DEVICE_ACTOR_CONDITION_VALUE_BOT"),
            Self::DeviceActorConditionValueAgent => write!(f, "DEVICE_ACTOR_CONDITION_VALUE_AGENT"),
            Self::DeviceActorConditionValueUnknown => write!(f, "DEVICE_ACTOR_CONDITION_VALUE_UNKNOWN"),
        }
    }
}

impl Default for DeviceActorConditionValue {
    fn default() -> DeviceActorConditionValue {
        Self::DeviceActorConditionValueUnspecified
    }
}

