/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DevicePlatformConditionTraceOption {
    #[serde(rename = "hasRoute", skip_serializing_if = "Option::is_none")]
    pub has_route: Option<bool>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "platformName", skip_serializing_if = "Option::is_none")]
    pub platform_name: Option<String>,
}

impl DevicePlatformConditionTraceOption {
    pub fn new() -> DevicePlatformConditionTraceOption {
        DevicePlatformConditionTraceOption {
            has_route: None,
            id: None,
            name: None,
            platform_name: None,
        }
    }
}

