/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.110.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DevicePlatformConditionOption : Device platform condition option for EVENT_ACTION_DEVICE_PLATFORM_CONDITION.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DevicePlatformConditionOption {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "nextStepId", skip_serializing_if = "Option::is_none")]
    pub next_step_id: Option<String>,
    /// Allowed values for device platform routing conditions.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<Value>,
}

impl DevicePlatformConditionOption {
    /// Device platform condition option for EVENT_ACTION_DEVICE_PLATFORM_CONDITION.
    pub fn new() -> DevicePlatformConditionOption {
        DevicePlatformConditionOption {
            id: None,
            name: None,
            next_step_id: None,
            value: None,
        }
    }
}
/// Allowed values for device platform routing conditions.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Value {
    #[serde(rename = "DEVICE_PLATFORM_CONDITION_VALUE_UNSPECIFIED")]
    DevicePlatformConditionValueUnspecified,
    #[serde(rename = "DEVICE_PLATFORM_CONDITION_VALUE_IOS")]
    DevicePlatformConditionValueIos,
    #[serde(rename = "DEVICE_PLATFORM_CONDITION_VALUE_ANDROID")]
    DevicePlatformConditionValueAndroid,
    #[serde(rename = "DEVICE_PLATFORM_CONDITION_VALUE_WINDOWS")]
    DevicePlatformConditionValueWindows,
    #[serde(rename = "DEVICE_PLATFORM_CONDITION_VALUE_MACOS")]
    DevicePlatformConditionValueMacos,
    #[serde(rename = "DEVICE_PLATFORM_CONDITION_VALUE_LINUX")]
    DevicePlatformConditionValueLinux,
    #[serde(rename = "DEVICE_PLATFORM_CONDITION_VALUE_CHROMEOS")]
    DevicePlatformConditionValueChromeos,
}

impl Default for Value {
    fn default() -> Value {
        Self::DevicePlatformConditionValueUnspecified
    }
}

