/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeviceBrowserConditionValue : Allowed values for device browser routing conditions.
/// Allowed values for device browser routing conditions.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeviceBrowserConditionValue {
    #[serde(rename = "DEVICE_BROWSER_CONDITION_VALUE_UNSPECIFIED")]
    DeviceBrowserConditionValueUnspecified,
    #[serde(rename = "DEVICE_BROWSER_CONDITION_VALUE_CHROME")]
    DeviceBrowserConditionValueChrome,
    #[serde(rename = "DEVICE_BROWSER_CONDITION_VALUE_SAFARI")]
    DeviceBrowserConditionValueSafari,
    #[serde(rename = "DEVICE_BROWSER_CONDITION_VALUE_FIREFOX")]
    DeviceBrowserConditionValueFirefox,
    #[serde(rename = "DEVICE_BROWSER_CONDITION_VALUE_EDGE")]
    DeviceBrowserConditionValueEdge,
    #[serde(rename = "DEVICE_BROWSER_CONDITION_VALUE_OPERA")]
    DeviceBrowserConditionValueOpera,
    #[serde(rename = "DEVICE_BROWSER_CONDITION_VALUE_SAMSUNG_BROWSER")]
    DeviceBrowserConditionValueSamsungBrowser,

}

impl std::fmt::Display for DeviceBrowserConditionValue {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DeviceBrowserConditionValueUnspecified => write!(f, "DEVICE_BROWSER_CONDITION_VALUE_UNSPECIFIED"),
            Self::DeviceBrowserConditionValueChrome => write!(f, "DEVICE_BROWSER_CONDITION_VALUE_CHROME"),
            Self::DeviceBrowserConditionValueSafari => write!(f, "DEVICE_BROWSER_CONDITION_VALUE_SAFARI"),
            Self::DeviceBrowserConditionValueFirefox => write!(f, "DEVICE_BROWSER_CONDITION_VALUE_FIREFOX"),
            Self::DeviceBrowserConditionValueEdge => write!(f, "DEVICE_BROWSER_CONDITION_VALUE_EDGE"),
            Self::DeviceBrowserConditionValueOpera => write!(f, "DEVICE_BROWSER_CONDITION_VALUE_OPERA"),
            Self::DeviceBrowserConditionValueSamsungBrowser => write!(f, "DEVICE_BROWSER_CONDITION_VALUE_SAMSUNG_BROWSER"),
        }
    }
}

impl Default for DeviceBrowserConditionValue {
    fn default() -> DeviceBrowserConditionValue {
        Self::DeviceBrowserConditionValueUnspecified
    }
}

