/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceBrowserConditionTraceOption {
    #[serde(rename = "browserName", skip_serializing_if = "Option::is_none")]
    pub browser_name: Option<String>,
    #[serde(rename = "hasRoute", skip_serializing_if = "Option::is_none")]
    pub has_route: Option<bool>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl DeviceBrowserConditionTraceOption {
    pub fn new() -> DeviceBrowserConditionTraceOption {
        DeviceBrowserConditionTraceOption {
            browser_name: None,
            has_route: None,
            id: None,
            name: None,
        }
    }
}

