/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.45.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeviceActor : DeviceActor represents WHO or WHAT is operating the device. This distinguishes between a real human visitor, an automated crawler/scraper bot (e.g. Googlebot, BingBot), and an AI/LLM agent acting on behalf of a user (e.g. GPTBot, ClaudeBot, Gemini, Grok).   - DEVICE_ACTOR_UNSPECIFIED: Actor not specified or not yet detected  - DEVICE_ACTOR_HUMAN: Human visitor using a browser (covers MOBILE, TABLET, DESKTOP device types)  - DEVICE_ACTOR_BOT: Automated crawler or scraper bot (e.g. Googlebot, BingBot, Applebot)  - DEVICE_ACTOR_AGENT: AI/LLM agent browsing on behalf of a user (e.g. GPTBot, ClaudeBot, Gemini, Grok)  - DEVICE_ACTOR_UNKNOWN: Unable to classify the actor
/// DeviceActor represents WHO or WHAT is operating the device. This distinguishes between a real human visitor, an automated crawler/scraper bot (e.g. Googlebot, BingBot), and an AI/LLM agent acting on behalf of a user (e.g. GPTBot, ClaudeBot, Gemini, Grok).   - DEVICE_ACTOR_UNSPECIFIED: Actor not specified or not yet detected  - DEVICE_ACTOR_HUMAN: Human visitor using a browser (covers MOBILE, TABLET, DESKTOP device types)  - DEVICE_ACTOR_BOT: Automated crawler or scraper bot (e.g. Googlebot, BingBot, Applebot)  - DEVICE_ACTOR_AGENT: AI/LLM agent browsing on behalf of a user (e.g. GPTBot, ClaudeBot, Gemini, Grok)  - DEVICE_ACTOR_UNKNOWN: Unable to classify the actor
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeviceActor {
    #[serde(rename = "DEVICE_ACTOR_UNSPECIFIED")]
    DeviceActorUnspecified,
    #[serde(rename = "DEVICE_ACTOR_HUMAN")]
    DeviceActorHuman,
    #[serde(rename = "DEVICE_ACTOR_BOT")]
    DeviceActorBot,
    #[serde(rename = "DEVICE_ACTOR_AGENT")]
    DeviceActorAgent,
    #[serde(rename = "DEVICE_ACTOR_UNKNOWN")]
    DeviceActorUnknown,

}

impl std::fmt::Display for DeviceActor {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DeviceActorUnspecified => write!(f, "DEVICE_ACTOR_UNSPECIFIED"),
            Self::DeviceActorHuman => write!(f, "DEVICE_ACTOR_HUMAN"),
            Self::DeviceActorBot => write!(f, "DEVICE_ACTOR_BOT"),
            Self::DeviceActorAgent => write!(f, "DEVICE_ACTOR_AGENT"),
            Self::DeviceActorUnknown => write!(f, "DEVICE_ACTOR_UNKNOWN"),
        }
    }
}

impl Default for DeviceActor {
    fn default() -> DeviceActor {
        Self::DeviceActorUnspecified
    }
}

