/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.45.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeviceActorConditionTraceData : DeviceActorConditionTraceData stores device actor routing metadata.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceActorConditionTraceData {
    #[serde(rename = "deviceActor", skip_serializing_if = "Option::is_none")]
    pub device_actor: Option<String>,
    #[serde(rename = "hasElse", skip_serializing_if = "Option::is_none")]
    pub has_else: Option<bool>,
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Vec<models::DeviceActorConditionTraceOption>>,
}

impl DeviceActorConditionTraceData {
    /// DeviceActorConditionTraceData stores device actor routing metadata.
    pub fn new() -> DeviceActorConditionTraceData {
        DeviceActorConditionTraceData {
            device_actor: None,
            has_else: None,
            options: None,
        }
    }
}

