/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceBrandConditionPayload {
    #[serde(rename = "elseNextStepId", skip_serializing_if = "Option::is_none")]
    pub else_next_step_id: Option<String>,
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Vec<models::DeviceBrandConditionOption>>,
}

impl DeviceBrandConditionPayload {
    pub fn new() -> DeviceBrandConditionPayload {
        DeviceBrandConditionPayload {
            else_next_step_id: None,
            options: None,
        }
    }
}

