/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.115.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DisconnectWorkflowStepResponse {
    #[serde(rename = "disconnectedSteps", skip_serializing_if = "Option::is_none")]
    pub disconnected_steps: Option<Vec<models::WorkflowIssue>>,
    #[serde(rename = "unconnectedBranchIds", skip_serializing_if = "Option::is_none")]
    pub unconnected_branch_ids: Option<Vec<String>>,
    #[serde(rename = "workflowStep", skip_serializing_if = "Option::is_none")]
    pub workflow_step: Option<Box<models::WorkflowStep>>,
}

impl DisconnectWorkflowStepResponse {
    pub fn new() -> DisconnectWorkflowStepResponse {
        DisconnectWorkflowStepResponse {
            disconnected_steps: None,
            unconnected_branch_ids: None,
            workflow_step: None,
        }
    }
}

