/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.143.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DnsRecordPurpose : - DNS_RECORD_PURPOSE_UNSPECIFIED: Not specified  - DNS_RECORD_PURPOSE_ROUTING: Sends the domain's traffic to Linkbreakers  - DNS_RECORD_PURPOSE_CERTIFICATE_DELEGATION: Lets the certificate provider issue and renew the HTTPS certificate on its own  - DNS_RECORD_PURPOSE_OWNERSHIP: Proves ownership of the domain  - DNS_RECORD_PURPOSE_CERTIFICATE_VALIDATION: Validates the certificate currently being issued
/// - DNS_RECORD_PURPOSE_UNSPECIFIED: Not specified  - DNS_RECORD_PURPOSE_ROUTING: Sends the domain's traffic to Linkbreakers  - DNS_RECORD_PURPOSE_CERTIFICATE_DELEGATION: Lets the certificate provider issue and renew the HTTPS certificate on its own  - DNS_RECORD_PURPOSE_OWNERSHIP: Proves ownership of the domain  - DNS_RECORD_PURPOSE_CERTIFICATE_VALIDATION: Validates the certificate currently being issued
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DnsRecordPurpose {
    #[serde(rename = "DNS_RECORD_PURPOSE_UNSPECIFIED")]
    DnsRecordPurposeUnspecified,
    #[serde(rename = "DNS_RECORD_PURPOSE_ROUTING")]
    DnsRecordPurposeRouting,
    #[serde(rename = "DNS_RECORD_PURPOSE_CERTIFICATE_DELEGATION")]
    DnsRecordPurposeCertificateDelegation,
    #[serde(rename = "DNS_RECORD_PURPOSE_OWNERSHIP")]
    DnsRecordPurposeOwnership,
    #[serde(rename = "DNS_RECORD_PURPOSE_CERTIFICATE_VALIDATION")]
    DnsRecordPurposeCertificateValidation,

}

impl std::fmt::Display for DnsRecordPurpose {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DnsRecordPurposeUnspecified => write!(f, "DNS_RECORD_PURPOSE_UNSPECIFIED"),
            Self::DnsRecordPurposeRouting => write!(f, "DNS_RECORD_PURPOSE_ROUTING"),
            Self::DnsRecordPurposeCertificateDelegation => write!(f, "DNS_RECORD_PURPOSE_CERTIFICATE_DELEGATION"),
            Self::DnsRecordPurposeOwnership => write!(f, "DNS_RECORD_PURPOSE_OWNERSHIP"),
            Self::DnsRecordPurposeCertificateValidation => write!(f, "DNS_RECORD_PURPOSE_CERTIFICATE_VALIDATION"),
        }
    }
}

impl Default for DnsRecordPurpose {
    fn default() -> DnsRecordPurpose {
        Self::DnsRecordPurposeUnspecified
    }
}

