/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.147.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DnsProvider : - DNS_PROVIDER_UNSPECIFIED: Not detected  - DNS_PROVIDER_UNKNOWN: The nameservers do not match any provider Linkbreakers knows
/// - DNS_PROVIDER_UNSPECIFIED: Not detected  - DNS_PROVIDER_UNKNOWN: The nameservers do not match any provider Linkbreakers knows
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DnsProvider {
    #[serde(rename = "DNS_PROVIDER_UNSPECIFIED")]
    DnsProviderUnspecified,
    #[serde(rename = "DNS_PROVIDER_UNKNOWN")]
    DnsProviderUnknown,
    #[serde(rename = "DNS_PROVIDER_CLOUDFLARE")]
    DnsProviderCloudflare,
    #[serde(rename = "DNS_PROVIDER_GODADDY")]
    DnsProviderGodaddy,
    #[serde(rename = "DNS_PROVIDER_NAMECHEAP")]
    DnsProviderNamecheap,
    #[serde(rename = "DNS_PROVIDER_SQUARESPACE")]
    DnsProviderSquarespace,
    #[serde(rename = "DNS_PROVIDER_IONOS")]
    DnsProviderIonos,
    #[serde(rename = "DNS_PROVIDER_OVHCLOUD")]
    DnsProviderOvhcloud,
    #[serde(rename = "DNS_PROVIDER_GANDI")]
    DnsProviderGandi,
    #[serde(rename = "DNS_PROVIDER_HOSTINGER")]
    DnsProviderHostinger,
    #[serde(rename = "DNS_PROVIDER_WIX")]
    DnsProviderWix,
    #[serde(rename = "DNS_PROVIDER_AWS_ROUTE53")]
    DnsProviderAwsRoute53,
    #[serde(rename = "DNS_PROVIDER_GOOGLE_CLOUD_DNS")]
    DnsProviderGoogleCloudDns,
    #[serde(rename = "DNS_PROVIDER_DIGITALOCEAN")]
    DnsProviderDigitalocean,
    #[serde(rename = "DNS_PROVIDER_VERCEL")]
    DnsProviderVercel,
    #[serde(rename = "DNS_PROVIDER_PORKBUN")]
    DnsProviderPorkbun,
    #[serde(rename = "DNS_PROVIDER_NAME_COM")]
    DnsProviderNameCom,
    #[serde(rename = "DNS_PROVIDER_HOVER")]
    DnsProviderHover,
    #[serde(rename = "DNS_PROVIDER_NETWORK_SOLUTIONS")]
    DnsProviderNetworkSolutions,
    #[serde(rename = "DNS_PROVIDER_BLUEHOST")]
    DnsProviderBluehost,
    #[serde(rename = "DNS_PROVIDER_NETLIFY")]
    DnsProviderNetlify,
    #[serde(rename = "DNS_PROVIDER_AZURE_DNS")]
    DnsProviderAzureDns,
    #[serde(rename = "DNS_PROVIDER_DYNADOT")]
    DnsProviderDynadot,
    #[serde(rename = "DNS_PROVIDER_NAMESILO")]
    DnsProviderNamesilo,

}

impl std::fmt::Display for DnsProvider {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DnsProviderUnspecified => write!(f, "DNS_PROVIDER_UNSPECIFIED"),
            Self::DnsProviderUnknown => write!(f, "DNS_PROVIDER_UNKNOWN"),
            Self::DnsProviderCloudflare => write!(f, "DNS_PROVIDER_CLOUDFLARE"),
            Self::DnsProviderGodaddy => write!(f, "DNS_PROVIDER_GODADDY"),
            Self::DnsProviderNamecheap => write!(f, "DNS_PROVIDER_NAMECHEAP"),
            Self::DnsProviderSquarespace => write!(f, "DNS_PROVIDER_SQUARESPACE"),
            Self::DnsProviderIonos => write!(f, "DNS_PROVIDER_IONOS"),
            Self::DnsProviderOvhcloud => write!(f, "DNS_PROVIDER_OVHCLOUD"),
            Self::DnsProviderGandi => write!(f, "DNS_PROVIDER_GANDI"),
            Self::DnsProviderHostinger => write!(f, "DNS_PROVIDER_HOSTINGER"),
            Self::DnsProviderWix => write!(f, "DNS_PROVIDER_WIX"),
            Self::DnsProviderAwsRoute53 => write!(f, "DNS_PROVIDER_AWS_ROUTE53"),
            Self::DnsProviderGoogleCloudDns => write!(f, "DNS_PROVIDER_GOOGLE_CLOUD_DNS"),
            Self::DnsProviderDigitalocean => write!(f, "DNS_PROVIDER_DIGITALOCEAN"),
            Self::DnsProviderVercel => write!(f, "DNS_PROVIDER_VERCEL"),
            Self::DnsProviderPorkbun => write!(f, "DNS_PROVIDER_PORKBUN"),
            Self::DnsProviderNameCom => write!(f, "DNS_PROVIDER_NAME_COM"),
            Self::DnsProviderHover => write!(f, "DNS_PROVIDER_HOVER"),
            Self::DnsProviderNetworkSolutions => write!(f, "DNS_PROVIDER_NETWORK_SOLUTIONS"),
            Self::DnsProviderBluehost => write!(f, "DNS_PROVIDER_BLUEHOST"),
            Self::DnsProviderNetlify => write!(f, "DNS_PROVIDER_NETLIFY"),
            Self::DnsProviderAzureDns => write!(f, "DNS_PROVIDER_AZURE_DNS"),
            Self::DnsProviderDynadot => write!(f, "DNS_PROVIDER_DYNADOT"),
            Self::DnsProviderNamesilo => write!(f, "DNS_PROVIDER_NAMESILO"),
        }
    }
}

impl Default for DnsProvider {
    fn default() -> DnsProvider {
        Self::DnsProviderUnspecified
    }
}

