/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.81.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DotsType {
    #[serde(rename = "DOTS_TYPE_UNSPECIFIED")]
    DotsTypeUnspecified,
    #[serde(rename = "DOTS_TYPE_SQUARE")]
    DotsTypeSquare,
    #[serde(rename = "DOTS_TYPE_DOTS")]
    DotsTypeDots,
    #[serde(rename = "DOTS_TYPE_BUBBLY_DOTS")]
    DotsTypeBubblyDots,
    #[serde(rename = "DOTS_TYPE_CIRCUIT_CHIP")]
    DotsTypeCircuitChip,
    #[serde(rename = "DOTS_TYPE_ROUNDED")]
    DotsTypeRounded,
    #[serde(rename = "DOTS_TYPE_EXTRA_ROUNDED")]
    DotsTypeExtraRounded,
    #[serde(rename = "DOTS_TYPE_CLASSY")]
    DotsTypeClassy,
    #[serde(rename = "DOTS_TYPE_CLASSY_ROUNDED")]
    DotsTypeClassyRounded,
    #[serde(rename = "DOTS_TYPE_HEXAGON")]
    DotsTypeHexagon,
    #[serde(rename = "DOTS_TYPE_OCTAGON")]
    DotsTypeOctagon,

}

impl std::fmt::Display for DotsType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DotsTypeUnspecified => write!(f, "DOTS_TYPE_UNSPECIFIED"),
            Self::DotsTypeSquare => write!(f, "DOTS_TYPE_SQUARE"),
            Self::DotsTypeDots => write!(f, "DOTS_TYPE_DOTS"),
            Self::DotsTypeBubblyDots => write!(f, "DOTS_TYPE_BUBBLY_DOTS"),
            Self::DotsTypeCircuitChip => write!(f, "DOTS_TYPE_CIRCUIT_CHIP"),
            Self::DotsTypeRounded => write!(f, "DOTS_TYPE_ROUNDED"),
            Self::DotsTypeExtraRounded => write!(f, "DOTS_TYPE_EXTRA_ROUNDED"),
            Self::DotsTypeClassy => write!(f, "DOTS_TYPE_CLASSY"),
            Self::DotsTypeClassyRounded => write!(f, "DOTS_TYPE_CLASSY_ROUNDED"),
            Self::DotsTypeHexagon => write!(f, "DOTS_TYPE_HEXAGON"),
            Self::DotsTypeOctagon => write!(f, "DOTS_TYPE_OCTAGON"),
        }
    }
}

impl Default for DotsType {
    fn default() -> DotsType {
        Self::DotsTypeUnspecified
    }
}

