/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.43.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EntryAccessTraceData : EntryAccessTraceData stores details for entry access traces.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntryAccessTraceData {
    #[serde(rename = "accessedAt", skip_serializing_if = "Option::is_none")]
    pub accessed_at: Option<String>,
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<String>,
    #[serde(rename = "entrypoint", skip_serializing_if = "Option::is_none")]
    pub entrypoint: Option<String>,
    #[serde(rename = "httpMethod", skip_serializing_if = "Option::is_none")]
    pub http_method: Option<String>,
    #[serde(rename = "visitType", skip_serializing_if = "Option::is_none")]
    pub visit_type: Option<String>,
}

impl EntryAccessTraceData {
    /// EntryAccessTraceData stores details for entry access traces.
    pub fn new() -> EntryAccessTraceData {
        EntryAccessTraceData {
            accessed_at: None,
            action: None,
            entrypoint: None,
            http_method: None,
            visit_type: None,
        }
    }
}

