/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventsTimeSeries {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<models::EventsTimeSeriesData>>,
    #[serde(rename = "totalData", skip_serializing_if = "Option::is_none")]
    pub total_data: Option<i32>,
    #[serde(rename = "totalIntervals", skip_serializing_if = "Option::is_none")]
    pub total_intervals: Option<i32>,
}

impl EventsTimeSeries {
    pub fn new() -> EventsTimeSeries {
        EventsTimeSeries {
            data: None,
            total_data: None,
            total_intervals: None,
        }
    }
}

