/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.43.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FormTraceData : FormTraceData stores summary data about a form interaction.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FormTraceData {
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<String>,
    #[serde(rename = "autoSkipIfKnown", skip_serializing_if = "Option::is_none")]
    pub auto_skip_if_known: Option<bool>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "fields", skip_serializing_if = "Option::is_none")]
    pub fields: Option<Vec<models::FormTraceDataField>>,
    #[serde(rename = "skipButtonText", skip_serializing_if = "Option::is_none")]
    pub skip_button_text: Option<String>,
    #[serde(rename = "skipMethod", skip_serializing_if = "Option::is_none")]
    pub skip_method: Option<String>,
    #[serde(rename = "skipped", skip_serializing_if = "Option::is_none")]
    pub skipped: Option<bool>,
    #[serde(rename = "submitButtonText", skip_serializing_if = "Option::is_none")]
    pub submit_button_text: Option<String>,
    #[serde(rename = "submittedFields", skip_serializing_if = "Option::is_none")]
    pub submitted_fields: Option<i32>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "totalFields", skip_serializing_if = "Option::is_none")]
    pub total_fields: Option<i32>,
}

impl FormTraceData {
    /// FormTraceData stores summary data about a form interaction.
    pub fn new() -> FormTraceData {
        FormTraceData {
            action: None,
            auto_skip_if_known: None,
            description: None,
            fields: None,
            skip_button_text: None,
            skip_method: None,
            skipped: None,
            submit_button_text: None,
            submitted_fields: None,
            title: None,
            total_fields: None,
        }
    }
}

