/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.43.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FormFieldType : - FORM_FIELD_TYPE_UNSPECIFIED: Form field type not specified
/// - FORM_FIELD_TYPE_UNSPECIFIED: Form field type not specified
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FormFieldType {
    #[serde(rename = "FORM_FIELD_TYPE_UNSPECIFIED")]
    FormFieldTypeUnspecified,
    #[serde(rename = "FORM_FIELD_TYPE_TEXT")]
    FormFieldTypeText,
    #[serde(rename = "FORM_FIELD_TYPE_EMAIL")]
    FormFieldTypeEmail,
    #[serde(rename = "FORM_FIELD_TYPE_PHONE")]
    FormFieldTypePhone,
    #[serde(rename = "FORM_FIELD_TYPE_TEXTAREA")]
    FormFieldTypeTextarea,
    #[serde(rename = "FORM_FIELD_TYPE_RADIO")]
    FormFieldTypeRadio,
    #[serde(rename = "FORM_FIELD_TYPE_CHECKBOX")]
    FormFieldTypeCheckbox,
    #[serde(rename = "FORM_FIELD_TYPE_DROPDOWN")]
    FormFieldTypeDropdown,
    #[serde(rename = "FORM_FIELD_TYPE_NUMBER")]
    FormFieldTypeNumber,
    #[serde(rename = "FORM_FIELD_TYPE_DATE")]
    FormFieldTypeDate,
    #[serde(rename = "FORM_FIELD_TYPE_RATING")]
    FormFieldTypeRating,

}

impl std::fmt::Display for FormFieldType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::FormFieldTypeUnspecified => write!(f, "FORM_FIELD_TYPE_UNSPECIFIED"),
            Self::FormFieldTypeText => write!(f, "FORM_FIELD_TYPE_TEXT"),
            Self::FormFieldTypeEmail => write!(f, "FORM_FIELD_TYPE_EMAIL"),
            Self::FormFieldTypePhone => write!(f, "FORM_FIELD_TYPE_PHONE"),
            Self::FormFieldTypeTextarea => write!(f, "FORM_FIELD_TYPE_TEXTAREA"),
            Self::FormFieldTypeRadio => write!(f, "FORM_FIELD_TYPE_RADIO"),
            Self::FormFieldTypeCheckbox => write!(f, "FORM_FIELD_TYPE_CHECKBOX"),
            Self::FormFieldTypeDropdown => write!(f, "FORM_FIELD_TYPE_DROPDOWN"),
            Self::FormFieldTypeNumber => write!(f, "FORM_FIELD_TYPE_NUMBER"),
            Self::FormFieldTypeDate => write!(f, "FORM_FIELD_TYPE_DATE"),
            Self::FormFieldTypeRating => write!(f, "FORM_FIELD_TYPE_RATING"),
        }
    }
}

impl Default for FormFieldType {
    fn default() -> FormFieldType {
        Self::FormFieldTypeUnspecified
    }
}

