/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.113.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FunnelBranch : FunnelBranch is one choice within a step, such as a button on a multi-link page.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunnelBranch {
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "shareOfStep", skip_serializing_if = "Option::is_none")]
    pub share_of_step: Option<f64>,
    /// Journeys that took this branch. Zero means it was offered and nobody took it, which is worth seeing rather than hiding.
    #[serde(rename = "visits", skip_serializing_if = "Option::is_none")]
    pub visits: Option<String>,
}

impl FunnelBranch {
    /// FunnelBranch is one choice within a step, such as a button on a multi-link page.
    pub fn new() -> FunnelBranch {
        FunnelBranch {
            label: None,
            share_of_step: None,
            visits: None,
        }
    }
}

