/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.44.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLeadScoreExplanationResponse {
    #[serde(rename = "breakdown", skip_serializing_if = "Option::is_none")]
    pub breakdown: Option<Box<models::LeadScoreBreakdown>>,
    #[serde(rename = "explanation", skip_serializing_if = "Option::is_none")]
    pub explanation: Option<String>,
    #[serde(rename = "leadScore", skip_serializing_if = "Option::is_none")]
    pub lead_score: Option<i32>,
    #[serde(rename = "recurringScans", skip_serializing_if = "Option::is_none")]
    pub recurring_scans: Option<i32>,
}

impl GetLeadScoreExplanationResponse {
    pub fn new() -> GetLeadScoreExplanationResponse {
        GetLeadScoreExplanationResponse {
            breakdown: None,
            explanation: None,
            lead_score: None,
            recurring_scans: None,
        }
    }
}

