/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.80.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetGoogleFormsOAuthUrlResponse {
    #[serde(rename = "oauthUrl", skip_serializing_if = "Option::is_none")]
    pub oauth_url: Option<String>,
}

impl GetGoogleFormsOAuthUrlResponse {
    pub fn new() -> GetGoogleFormsOAuthUrlResponse {
        GetGoogleFormsOAuthUrlResponse {
            oauth_url: None,
        }
    }
}

