/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.122.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetHourOfDayDistributionResponse {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<models::HourOfDayDataPoint>>,
    #[serde(rename = "totalEvents", skip_serializing_if = "Option::is_none")]
    pub total_events: Option<i32>,
}

impl GetHourOfDayDistributionResponse {
    pub fn new() -> GetHourOfDayDistributionResponse {
        GetHourOfDayDistributionResponse {
            data: None,
            total_events: None,
        }
    }
}

