/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.86.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetVisitorTrendsResponse {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<models::VisitorTrendDataPoint>>,
    #[serde(rename = "totalNew", skip_serializing_if = "Option::is_none")]
    pub total_new: Option<i32>,
    #[serde(rename = "totalReturning", skip_serializing_if = "Option::is_none")]
    pub total_returning: Option<i32>,
}

impl GetVisitorTrendsResponse {
    pub fn new() -> GetVisitorTrendsResponse {
        GetVisitorTrendsResponse {
            data: None,
            total_new: None,
            total_returning: None,
        }
    }
}

