/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.55.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetGoogleFormFieldsResponse {
    #[serde(rename = "fields", skip_serializing_if = "Option::is_none")]
    pub fields: Option<Vec<models::GoogleFormField>>,
}

impl GetGoogleFormFieldsResponse {
    pub fn new() -> GetGoogleFormFieldsResponse {
        GetGoogleFormFieldsResponse {
            fields: None,
        }
    }
}

