/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.121.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLeadScoreResponse {
    /// Breakdown of the scoring factors. A factor that is absent was not measurable for this visitor and was excluded from the score.
    #[serde(rename = "breakdown", skip_serializing_if = "Option::is_none")]
    pub breakdown: Option<Box<models::LeadScoreBreakdown>>,
    #[serde(rename = "leadScore", skip_serializing_if = "Option::is_none")]
    pub lead_score: Option<i32>,
    #[serde(rename = "recurringScans", skip_serializing_if = "Option::is_none")]
    pub recurring_scans: Option<i32>,
    /// How this link was classified when its weighting was derived, for example \"b2b_enterprise\" or \"community_social\".
    #[serde(rename = "scoringContext", skip_serializing_if = "Option::is_none")]
    pub scoring_context: Option<String>,
    /// Plain explanation of why the link is weighted the way it is. Empty when the link scores on the deterministic weighting.
    #[serde(rename = "scoringRationale", skip_serializing_if = "Option::is_none")]
    pub scoring_rationale: Option<String>,
}

impl GetLeadScoreResponse {
    pub fn new() -> GetLeadScoreResponse {
        GetLeadScoreResponse {
            breakdown: None,
            lead_score: None,
            recurring_scans: None,
            scoring_context: None,
            scoring_rationale: None,
        }
    }
}

