/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetQrcodeDesignResponse : GetQrcodeDesignResponse returns the design definition hydrated with computed fields.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetQrcodeDesignResponse {
    #[serde(rename = "qrcodeDesign", skip_serializing_if = "Option::is_none")]
    pub qrcode_design: Option<Box<models::QrcodeDesign>>,
}

impl GetQrcodeDesignResponse {
    /// GetQrcodeDesignResponse returns the design definition hydrated with computed fields.
    pub fn new() -> GetQrcodeDesignResponse {
        GetQrcodeDesignResponse {
            qrcode_design: None,
        }
    }
}

