/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.118.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetStepFunnelRequest : GetStepFunnelRequest asks how far visitors get through a link's workflow.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetStepFunnelRequest {
    #[serde(rename = "endDate", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<String>,
    #[serde(rename = "linkId", skip_serializing_if = "Option::is_none")]
    pub link_id: Option<String>,
    #[serde(rename = "startDate", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<String>,
}

impl GetStepFunnelRequest {
    /// GetStepFunnelRequest asks how far visitors get through a link's workflow.
    pub fn new() -> GetStepFunnelRequest {
        GetStepFunnelRequest {
            end_date: None,
            link_id: None,
            start_date: None,
        }
    }
}

