/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.45.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetLinkSettingResponse : GetLinkSettingResponse returns the link-setting profile for inspection in the dashboard.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLinkSettingResponse {
    #[serde(rename = "linkSetting", skip_serializing_if = "Option::is_none")]
    pub link_setting: Option<Box<models::LinkSetting>>,
}

impl GetLinkSettingResponse {
    /// GetLinkSettingResponse returns the link-setting profile for inspection in the dashboard.
    pub fn new() -> GetLinkSettingResponse {
        GetLinkSettingResponse {
            link_setting: None,
        }
    }
}

