/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.114.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetAttributeValuesRequest : GetAttributeValuesRequest lists individual values of one attribute, for free text such as comments where a distribution would be meaningless.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAttributeValuesRequest {
    #[serde(rename = "endDate", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<String>,
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    #[serde(rename = "linkId", skip_serializing_if = "Option::is_none")]
    pub link_id: Option<String>,
    #[serde(rename = "startDate", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<String>,
}

impl GetAttributeValuesRequest {
    /// GetAttributeValuesRequest lists individual values of one attribute, for free text such as comments where a distribution would be meaningless.
    pub fn new() -> GetAttributeValuesRequest {
        GetAttributeValuesRequest {
            end_date: None,
            key: None,
            limit: None,
            link_id: None,
            start_date: None,
        }
    }
}

