/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.55.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GoogleForm {
    #[serde(rename = "formId", skip_serializing_if = "Option::is_none")]
    pub form_id: Option<String>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
}

impl GoogleForm {
    pub fn new() -> GoogleForm {
        GoogleForm {
            form_id: None,
            title: None,
        }
    }
}

