/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.123.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GoogleFormsIntegration : GoogleFormsIntegration represents a connected Google account. Forms are auto-detected from workflow steps — no manual configuration needed.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GoogleFormsIntegration {
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "createdBy", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
    #[serde(rename = "googleEmail", skip_serializing_if = "Option::is_none")]
    pub google_email: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "lastSyncedAt", skip_serializing_if = "Option::is_none")]
    pub last_synced_at: Option<String>,
    #[serde(rename = "responsesSynced", skip_serializing_if = "Option::is_none")]
    pub responses_synced: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::GoogleFormsIntegrationStatus>,
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(rename = "visitorsEnriched", skip_serializing_if = "Option::is_none")]
    pub visitors_enriched: Option<String>,
    #[serde(rename = "workspaceId", skip_serializing_if = "Option::is_none")]
    pub workspace_id: Option<String>,
}

impl GoogleFormsIntegration {
    /// GoogleFormsIntegration represents a connected Google account. Forms are auto-detected from workflow steps — no manual configuration needed.
    pub fn new() -> GoogleFormsIntegration {
        GoogleFormsIntegration {
            created_at: None,
            created_by: None,
            google_email: None,
            id: None,
            last_synced_at: None,
            responses_synced: None,
            status: None,
            updated_at: None,
            visitors_enriched: None,
            workspace_id: None,
        }
    }
}

