/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.55.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GoogleFormsIntegrationStatus : - GOOGLE_FORMS_INTEGRATION_STATUS_UNSPECIFIED: Status not specified  - GOOGLE_FORMS_INTEGRATION_STATUS_ACTIVE: Integration is active and syncing responses  - GOOGLE_FORMS_INTEGRATION_STATUS_PAUSED: Integration is paused by user action  - GOOGLE_FORMS_INTEGRATION_STATUS_DISCONNECTED: Integration is disconnected
/// - GOOGLE_FORMS_INTEGRATION_STATUS_UNSPECIFIED: Status not specified  - GOOGLE_FORMS_INTEGRATION_STATUS_ACTIVE: Integration is active and syncing responses  - GOOGLE_FORMS_INTEGRATION_STATUS_PAUSED: Integration is paused by user action  - GOOGLE_FORMS_INTEGRATION_STATUS_DISCONNECTED: Integration is disconnected
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GoogleFormsIntegrationStatus {
    #[serde(rename = "GOOGLE_FORMS_INTEGRATION_STATUS_UNSPECIFIED")]
    GoogleFormsIntegrationStatusUnspecified,
    #[serde(rename = "GOOGLE_FORMS_INTEGRATION_STATUS_ACTIVE")]
    GoogleFormsIntegrationStatusActive,
    #[serde(rename = "GOOGLE_FORMS_INTEGRATION_STATUS_PAUSED")]
    GoogleFormsIntegrationStatusPaused,
    #[serde(rename = "GOOGLE_FORMS_INTEGRATION_STATUS_DISCONNECTED")]
    GoogleFormsIntegrationStatusDisconnected,

}

impl std::fmt::Display for GoogleFormsIntegrationStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::GoogleFormsIntegrationStatusUnspecified => write!(f, "GOOGLE_FORMS_INTEGRATION_STATUS_UNSPECIFIED"),
            Self::GoogleFormsIntegrationStatusActive => write!(f, "GOOGLE_FORMS_INTEGRATION_STATUS_ACTIVE"),
            Self::GoogleFormsIntegrationStatusPaused => write!(f, "GOOGLE_FORMS_INTEGRATION_STATUS_PAUSED"),
            Self::GoogleFormsIntegrationStatusDisconnected => write!(f, "GOOGLE_FORMS_INTEGRATION_STATUS_DISCONNECTED"),
        }
    }
}

impl Default for GoogleFormsIntegrationStatus {
    fn default() -> GoogleFormsIntegrationStatus {
        Self::GoogleFormsIntegrationStatusUnspecified
    }
}

