/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IdentifyResponse {
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<bool>,
    #[serde(rename = "visitor", skip_serializing_if = "Option::is_none")]
    pub visitor: Option<Box<models::Visitor>>,
}

impl IdentifyResponse {
    pub fn new() -> IdentifyResponse {
        IdentifyResponse {
            created: None,
            visitor: None,
        }
    }
}

