/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.14
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IdentifyVisitorTraceData : IdentifyVisitorTraceData stores visitor identification enrichment metadata.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IdentifyVisitorTraceData {
    #[serde(rename = "customAttributes", skip_serializing_if = "Option::is_none")]
    pub custom_attributes: Option<i32>,
    #[serde(rename = "fieldsUpdated", skip_serializing_if = "Option::is_none")]
    pub fields_updated: Option<i32>,
    #[serde(rename = "setOnce", skip_serializing_if = "Option::is_none")]
    pub set_once: Option<bool>,
    #[serde(rename = "systemFields", skip_serializing_if = "Option::is_none")]
    pub system_fields: Option<Vec<String>>,
}

impl IdentifyVisitorTraceData {
    /// IdentifyVisitorTraceData stores visitor identification enrichment metadata.
    pub fn new() -> IdentifyVisitorTraceData {
        IdentifyVisitorTraceData {
            custom_attributes: None,
            fields_updated: None,
            set_once: None,
            system_fields: None,
        }
    }
}

