/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LeadScoreBreakdown {
    #[serde(rename = "brandSupportiveness", skip_serializing_if = "Option::is_none")]
    pub brand_supportiveness: Option<i32>,
    #[serde(rename = "engagementLevel", skip_serializing_if = "Option::is_none")]
    pub engagement_level: Option<i32>,
    #[serde(rename = "profileFit", skip_serializing_if = "Option::is_none")]
    pub profile_fit: Option<i32>,
    #[serde(rename = "recurringInterest", skip_serializing_if = "Option::is_none")]
    pub recurring_interest: Option<i32>,
    #[serde(rename = "technologicalAptitude", skip_serializing_if = "Option::is_none")]
    pub technological_aptitude: Option<i32>,
}

impl LeadScoreBreakdown {
    pub fn new() -> LeadScoreBreakdown {
        LeadScoreBreakdown {
            brand_supportiveness: None,
            engagement_level: None,
            profile_fit: None,
            recurring_interest: None,
            technological_aptitude: None,
        }
    }
}

