/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LinkSetting : Stores per-link compliance preferences that drive how Linkbreakers collects visitor data before executing the workflow.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LinkSetting {
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "dataCollection", skip_serializing_if = "Option::is_none")]
    pub data_collection: Option<models::DataCollection>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl LinkSetting {
    /// Stores per-link compliance preferences that drive how Linkbreakers collects visitor data before executing the workflow.
    pub fn new() -> LinkSetting {
        LinkSetting {
            created_at: None,
            data_collection: None,
            id: None,
            updated_at: None,
        }
    }
}

