/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListDirectoriesResponse {
    #[serde(rename = "directories", skip_serializing_if = "Option::is_none")]
    pub directories: Option<Vec<models::Directory>>,
    /// Cursor to continue listing directories
    #[serde(rename = "nextPageToken", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
}

impl ListDirectoriesResponse {
    pub fn new() -> ListDirectoriesResponse {
        ListDirectoriesResponse {
            directories: None,
            next_page_token: None,
        }
    }
}

