/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListResponse : ListResponse wraps the current page of teammates for the workspace directory.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListResponse {
    #[serde(rename = "members", skip_serializing_if = "Option::is_none")]
    pub members: Option<Vec<models::Member>>,
}

impl ListResponse {
    /// ListResponse wraps the current page of teammates for the workspace directory.
    pub fn new() -> ListResponse {
        ListResponse {
            members: None,
        }
    }
}

