/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListEventsResponse : ListEventsResponse contains either the JSON payload or CSV export for the matching events.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListEventsResponse {
    #[serde(rename = "csv", skip_serializing_if = "Option::is_none")]
    pub csv: Option<Box<models::ListEventsCsvResponse>>,
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<Box<models::ListEventsJsonResponse>>,
}

impl ListEventsResponse {
    /// ListEventsResponse contains either the JSON payload or CSV export for the matching events.
    pub fn new() -> ListEventsResponse {
        ListEventsResponse {
            csv: None,
            json: None,
        }
    }
}

