/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.143.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListVisitorAttributeKeysResponse {
    /// Distinct selectable visitor attribute keys, including reserved system fields such as $email and $phone.
    #[serde(rename = "attributeKeys", skip_serializing_if = "Option::is_none")]
    pub attribute_keys: Option<Vec<String>>,
    /// The same keys with the type their values were captured as, so a client can offer the filter operators that fit each one.
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Vec<models::VisitorAttributeKey>>,
}

impl ListVisitorAttributeKeysResponse {
    pub fn new() -> ListVisitorAttributeKeysResponse {
        ListVisitorAttributeKeysResponse {
            attribute_keys: None,
            attributes: None,
        }
    }
}

