/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.87.7
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListSlackChannelsResponse {
    #[serde(rename = "channels", skip_serializing_if = "Option::is_none")]
    pub channels: Option<Vec<models::SlackChannel>>,
}

impl ListSlackChannelsResponse {
    pub fn new() -> ListSlackChannelsResponse {
        ListSlackChannelsResponse {
            channels: None,
        }
    }
}

