/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListEventsCsvResponse : ListEventsCsvResponse streams the export payload when ResponseFormat is set to RESPONSE_FORMAT_CSV.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListEventsCsvResponse {
    #[serde(rename = "contentType", skip_serializing_if = "Option::is_none")]
    pub content_type: Option<String>,
    #[serde(rename = "csvData", skip_serializing_if = "Option::is_none")]
    pub csv_data: Option<String>,
}

impl ListEventsCsvResponse {
    /// ListEventsCsvResponse streams the export payload when ResponseFormat is set to RESPONSE_FORMAT_CSV.
    pub fn new() -> ListEventsCsvResponse {
        ListEventsCsvResponse {
            content_type: None,
            csv_data: None,
        }
    }
}

