/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.147.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListPricingPlansResponse {
    /// Price of buying more credits. Absent when prices could not be read.
    #[serde(rename = "creditTopup", skip_serializing_if = "Option::is_none")]
    pub credit_topup: Option<Box<models::CreditTopup>>,
    #[serde(rename = "linkCreatedCreditCost", skip_serializing_if = "Option::is_none")]
    pub link_created_credit_cost: Option<i32>,
    #[serde(rename = "plans", skip_serializing_if = "Option::is_none")]
    pub plans: Option<Vec<models::PricingPlan>>,
    /// When the prices were read from the billing provider. Absent when they never could be.
    #[serde(rename = "pricesUpdatedAt", skip_serializing_if = "Option::is_none")]
    pub prices_updated_at: Option<String>,
}

impl ListPricingPlansResponse {
    pub fn new() -> ListPricingPlansResponse {
        ListPricingPlansResponse {
            credit_topup: None,
            link_created_credit_cost: None,
            plans: None,
            prices_updated_at: None,
        }
    }
}

