/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.9
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListEventsJsonResponse : ListEventsJsonResponse returns paginated event objects suitable for dashboards.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListEventsJsonResponse {
    #[serde(rename = "events", skip_serializing_if = "Option::is_none")]
    pub events: Option<Vec<models::Event>>,
    /// Whether there are more events beyond this page
    #[serde(rename = "hasMore", skip_serializing_if = "Option::is_none")]
    pub has_more: Option<bool>,
    /// Cursor token returned when another page is available
    #[serde(rename = "nextPageToken", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
    /// Total number of events matching the query
    #[serde(rename = "totalCount", skip_serializing_if = "Option::is_none")]
    pub total_count: Option<i64>,
}

impl ListEventsJsonResponse {
    /// ListEventsJsonResponse returns paginated event objects suitable for dashboards.
    pub fn new() -> ListEventsJsonResponse {
        ListEventsJsonResponse {
            events: None,
            has_more: None,
            next_page_token: None,
            total_count: None,
        }
    }
}

