/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.146.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListPageThemeTemplatesResponse {
    #[serde(rename = "hasMore", skip_serializing_if = "Option::is_none")]
    pub has_more: Option<bool>,
    /// Cursor token returned when another page is available
    #[serde(rename = "nextPageToken", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
    #[serde(rename = "pageThemeTemplates", skip_serializing_if = "Option::is_none")]
    pub page_theme_templates: Option<Vec<models::PageThemeTemplate>>,
    /// How many records exist in total, so a client can tell a complete answer from a page of one. A local-first client reads absence from this list as deletion, and may only do so when the count it was given matches what it received: without that, one page would look like the whole model and everything beyond it would be removed locally.
    #[serde(rename = "totalCount", skip_serializing_if = "Option::is_none")]
    pub total_count: Option<String>,
}

impl ListPageThemeTemplatesResponse {
    pub fn new() -> ListPageThemeTemplatesResponse {
        ListPageThemeTemplatesResponse {
            has_more: None,
            next_page_token: None,
            page_theme_templates: None,
            total_count: None,
        }
    }
}

