/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.45.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MediaSelection {
    #[serde(rename = "delete", skip_serializing_if = "Option::is_none")]
    pub delete: Option<serde_json::Value>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl MediaSelection {
    pub fn new() -> MediaSelection {
        MediaSelection {
            delete: None,
            id: None,
        }
    }
}

