/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MediaType : - TYPE_UNSPECIFIED: The media type is not specified  - TYPE_CENTRAL_QRCODE_IMAGE: The media type is a central QR code image  - TYPE_BACKGROUND_COVER: The media type is a background cover for page themes  - TYPE_BADGE: The media type is a badge image for page themes
/// - TYPE_UNSPECIFIED: The media type is not specified  - TYPE_CENTRAL_QRCODE_IMAGE: The media type is a central QR code image  - TYPE_BACKGROUND_COVER: The media type is a background cover for page themes  - TYPE_BADGE: The media type is a badge image for page themes
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MediaType {
    #[serde(rename = "TYPE_UNSPECIFIED")]
    TypeUnspecified,
    #[serde(rename = "TYPE_CENTRAL_QRCODE_IMAGE")]
    TypeCentralQrcodeImage,
    #[serde(rename = "TYPE_BACKGROUND_COVER")]
    TypeBackgroundCover,
    #[serde(rename = "TYPE_BADGE")]
    TypeBadge,

}

impl std::fmt::Display for MediaType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::TypeUnspecified => write!(f, "TYPE_UNSPECIFIED"),
            Self::TypeCentralQrcodeImage => write!(f, "TYPE_CENTRAL_QRCODE_IMAGE"),
            Self::TypeBackgroundCover => write!(f, "TYPE_BACKGROUND_COVER"),
            Self::TypeBadge => write!(f, "TYPE_BADGE"),
        }
    }
}

impl Default for MediaType {
    fn default() -> MediaType {
        Self::TypeUnspecified
    }
}

