/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.45.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MembersServiceUpdateBody : UpdateRequest enables admins to update another teammate's profile and role.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MembersServiceUpdateBody {
    #[serde(rename = "displayLanguage", skip_serializing_if = "Option::is_none")]
    pub display_language: Option<String>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "firstName", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    #[serde(rename = "lastName", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<models::Role>,
}

impl MembersServiceUpdateBody {
    /// UpdateRequest enables admins to update another teammate's profile and role.
    pub fn new() -> MembersServiceUpdateBody {
        MembersServiceUpdateBody {
            display_language: None,
            email: None,
            first_name: None,
            last_name: None,
            role: None,
        }
    }
}

