/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.101.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MessagePageNavigationType : - MESSAGE_PAGE_NAVIGATION_TYPE_UNSPECIFIED: Navigation type not specified  - MESSAGE_PAGE_NAVIGATION_TYPE_BUTTON: Visitor clicks a button to proceed  - MESSAGE_PAGE_NAVIGATION_TYPE_TIMER: Visitor is automatically redirected after a timer expires
/// - MESSAGE_PAGE_NAVIGATION_TYPE_UNSPECIFIED: Navigation type not specified  - MESSAGE_PAGE_NAVIGATION_TYPE_BUTTON: Visitor clicks a button to proceed  - MESSAGE_PAGE_NAVIGATION_TYPE_TIMER: Visitor is automatically redirected after a timer expires
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MessagePageNavigationType {
    #[serde(rename = "MESSAGE_PAGE_NAVIGATION_TYPE_UNSPECIFIED")]
    MessagePageNavigationTypeUnspecified,
    #[serde(rename = "MESSAGE_PAGE_NAVIGATION_TYPE_BUTTON")]
    MessagePageNavigationTypeButton,
    #[serde(rename = "MESSAGE_PAGE_NAVIGATION_TYPE_TIMER")]
    MessagePageNavigationTypeTimer,

}

impl std::fmt::Display for MessagePageNavigationType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::MessagePageNavigationTypeUnspecified => write!(f, "MESSAGE_PAGE_NAVIGATION_TYPE_UNSPECIFIED"),
            Self::MessagePageNavigationTypeButton => write!(f, "MESSAGE_PAGE_NAVIGATION_TYPE_BUTTON"),
            Self::MessagePageNavigationTypeTimer => write!(f, "MESSAGE_PAGE_NAVIGATION_TYPE_TIMER"),
        }
    }
}

impl Default for MessagePageNavigationType {
    fn default() -> MessagePageNavigationType {
        Self::MessagePageNavigationTypeUnspecified
    }
}

