/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.146.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MeteredUnit : - METERED_UNIT_UNSPECIFIED: Not set  - METERED_UNIT_LINK_CREATED: A link created  - METERED_UNIT_LINK_VISITED: A tracked visit  - METERED_UNIT_PUBLIC_API_CALL: A public API call  - METERED_UNIT_CUSTOM_DOMAIN_CREATED: A custom domain created
/// - METERED_UNIT_UNSPECIFIED: Not set  - METERED_UNIT_LINK_CREATED: A link created  - METERED_UNIT_LINK_VISITED: A tracked visit  - METERED_UNIT_PUBLIC_API_CALL: A public API call  - METERED_UNIT_CUSTOM_DOMAIN_CREATED: A custom domain created
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MeteredUnit {
    #[serde(rename = "METERED_UNIT_UNSPECIFIED")]
    MeteredUnitUnspecified,
    #[serde(rename = "METERED_UNIT_LINK_CREATED")]
    MeteredUnitLinkCreated,
    #[serde(rename = "METERED_UNIT_LINK_VISITED")]
    MeteredUnitLinkVisited,
    #[serde(rename = "METERED_UNIT_PUBLIC_API_CALL")]
    MeteredUnitPublicApiCall,
    #[serde(rename = "METERED_UNIT_CUSTOM_DOMAIN_CREATED")]
    MeteredUnitCustomDomainCreated,

}

impl std::fmt::Display for MeteredUnit {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::MeteredUnitUnspecified => write!(f, "METERED_UNIT_UNSPECIFIED"),
            Self::MeteredUnitLinkCreated => write!(f, "METERED_UNIT_LINK_CREATED"),
            Self::MeteredUnitLinkVisited => write!(f, "METERED_UNIT_LINK_VISITED"),
            Self::MeteredUnitPublicApiCall => write!(f, "METERED_UNIT_PUBLIC_API_CALL"),
            Self::MeteredUnitCustomDomainCreated => write!(f, "METERED_UNIT_CUSTOM_DOMAIN_CREATED"),
        }
    }
}

impl Default for MeteredUnit {
    fn default() -> MeteredUnit {
        Self::MeteredUnitUnspecified
    }
}

