/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.148.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MeteredPrice {
    #[serde(rename = "amounts", skip_serializing_if = "Option::is_none")]
    pub amounts: Option<Vec<models::Money>>,
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<models::MeteredUnit>,
}

impl MeteredPrice {
    pub fn new() -> MeteredPrice {
        MeteredPrice {
            amounts: None,
            unit: None,
        }
    }
}

