/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MultiLinkTraceSelectedButton : MultiLinkTraceSelectedButton stores the selected button metadata.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MultiLinkTraceSelectedButton {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "order", skip_serializing_if = "Option::is_none")]
    pub order: Option<i32>,
}

impl MultiLinkTraceSelectedButton {
    /// MultiLinkTraceSelectedButton stores the selected button metadata.
    pub fn new() -> MultiLinkTraceSelectedButton {
        MultiLinkTraceSelectedButton {
            id: None,
            label: None,
            order: None,
        }
    }
}

