/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MultiLinkTraceButton : MultiLinkTraceButton stores metadata for all buttons available on the multi-link page.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MultiLinkTraceButton {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "order", skip_serializing_if = "Option::is_none")]
    pub order: Option<i32>,
}

impl MultiLinkTraceButton {
    /// MultiLinkTraceButton stores metadata for all buttons available on the multi-link page.
    pub fn new() -> MultiLinkTraceButton {
        MultiLinkTraceButton {
            id: None,
            label: None,
            order: None,
        }
    }
}

