/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.45.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PageThemeBorderStyle {
    #[serde(rename = "PAGE_THEME_BORDER_STYLE_UNSPECIFIED")]
    PageThemeBorderStyleUnspecified,
    #[serde(rename = "PAGE_THEME_BORDER_STYLE_SOLID")]
    PageThemeBorderStyleSolid,
    #[serde(rename = "PAGE_THEME_BORDER_STYLE_DASHED")]
    PageThemeBorderStyleDashed,
    #[serde(rename = "PAGE_THEME_BORDER_STYLE_DOTTED")]
    PageThemeBorderStyleDotted,
    #[serde(rename = "PAGE_THEME_BORDER_STYLE_DOUBLE")]
    PageThemeBorderStyleDouble,
    #[serde(rename = "PAGE_THEME_BORDER_STYLE_GROOVE")]
    PageThemeBorderStyleGroove,
    #[serde(rename = "PAGE_THEME_BORDER_STYLE_RIDGE")]
    PageThemeBorderStyleRidge,

}

impl std::fmt::Display for PageThemeBorderStyle {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::PageThemeBorderStyleUnspecified => write!(f, "PAGE_THEME_BORDER_STYLE_UNSPECIFIED"),
            Self::PageThemeBorderStyleSolid => write!(f, "PAGE_THEME_BORDER_STYLE_SOLID"),
            Self::PageThemeBorderStyleDashed => write!(f, "PAGE_THEME_BORDER_STYLE_DASHED"),
            Self::PageThemeBorderStyleDotted => write!(f, "PAGE_THEME_BORDER_STYLE_DOTTED"),
            Self::PageThemeBorderStyleDouble => write!(f, "PAGE_THEME_BORDER_STYLE_DOUBLE"),
            Self::PageThemeBorderStyleGroove => write!(f, "PAGE_THEME_BORDER_STYLE_GROOVE"),
            Self::PageThemeBorderStyleRidge => write!(f, "PAGE_THEME_BORDER_STYLE_RIDGE"),
        }
    }
}

impl Default for PageThemeBorderStyle {
    fn default() -> PageThemeBorderStyle {
        Self::PageThemeBorderStyleUnspecified
    }
}

