/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.13
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PageThemeFontFamily :  - PAGE_THEME_FONT_FAMILY_UNSPECIFIED: Maps to the default system sans-serif stack.
///  - PAGE_THEME_FONT_FAMILY_UNSPECIFIED: Maps to the default system sans-serif stack.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PageThemeFontFamily {
    #[serde(rename = "PAGE_THEME_FONT_FAMILY_UNSPECIFIED")]
    PageThemeFontFamilyUnspecified,
    #[serde(rename = "PAGE_THEME_FONT_FAMILY_DEFAULT")]
    PageThemeFontFamilyDefault,
    #[serde(rename = "PAGE_THEME_FONT_FAMILY_ARIAL")]
    PageThemeFontFamilyArial,
    #[serde(rename = "PAGE_THEME_FONT_FAMILY_HELVETICA")]
    PageThemeFontFamilyHelvetica,
    #[serde(rename = "PAGE_THEME_FONT_FAMILY_VERDANA")]
    PageThemeFontFamilyVerdana,
    #[serde(rename = "PAGE_THEME_FONT_FAMILY_GEORGIA")]
    PageThemeFontFamilyGeorgia,
    #[serde(rename = "PAGE_THEME_FONT_FAMILY_TIMES_NEW_ROMAN")]
    PageThemeFontFamilyTimesNewRoman,
    #[serde(rename = "PAGE_THEME_FONT_FAMILY_COURIER_NEW")]
    PageThemeFontFamilyCourierNew,

}

impl std::fmt::Display for PageThemeFontFamily {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::PageThemeFontFamilyUnspecified => write!(f, "PAGE_THEME_FONT_FAMILY_UNSPECIFIED"),
            Self::PageThemeFontFamilyDefault => write!(f, "PAGE_THEME_FONT_FAMILY_DEFAULT"),
            Self::PageThemeFontFamilyArial => write!(f, "PAGE_THEME_FONT_FAMILY_ARIAL"),
            Self::PageThemeFontFamilyHelvetica => write!(f, "PAGE_THEME_FONT_FAMILY_HELVETICA"),
            Self::PageThemeFontFamilyVerdana => write!(f, "PAGE_THEME_FONT_FAMILY_VERDANA"),
            Self::PageThemeFontFamilyGeorgia => write!(f, "PAGE_THEME_FONT_FAMILY_GEORGIA"),
            Self::PageThemeFontFamilyTimesNewRoman => write!(f, "PAGE_THEME_FONT_FAMILY_TIMES_NEW_ROMAN"),
            Self::PageThemeFontFamilyCourierNew => write!(f, "PAGE_THEME_FONT_FAMILY_COURIER_NEW"),
        }
    }
}

impl Default for PageThemeFontFamily {
    fn default() -> PageThemeFontFamily {
        Self::PageThemeFontFamilyUnspecified
    }
}

