/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.7
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PageThemeContainerVariant {
    #[serde(rename = "PAGE_THEME_CONTAINER_VARIANT_UNSPECIFIED")]
    PageThemeContainerVariantUnspecified,
    #[serde(rename = "PAGE_THEME_CONTAINER_VARIANT_ROUNDED")]
    PageThemeContainerVariantRounded,
    #[serde(rename = "PAGE_THEME_CONTAINER_VARIANT_SQUARE")]
    PageThemeContainerVariantSquare,

}

impl std::fmt::Display for PageThemeContainerVariant {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::PageThemeContainerVariantUnspecified => write!(f, "PAGE_THEME_CONTAINER_VARIANT_UNSPECIFIED"),
            Self::PageThemeContainerVariantRounded => write!(f, "PAGE_THEME_CONTAINER_VARIANT_ROUNDED"),
            Self::PageThemeContainerVariantSquare => write!(f, "PAGE_THEME_CONTAINER_VARIANT_SQUARE"),
        }
    }
}

impl Default for PageThemeContainerVariant {
    fn default() -> PageThemeContainerVariant {
        Self::PageThemeContainerVariantUnspecified
    }
}

