/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.14
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PageThemeBadgeShape {
    #[serde(rename = "PAGE_THEME_BADGE_SHAPE_UNSPECIFIED")]
    PageThemeBadgeShapeUnspecified,
    #[serde(rename = "PAGE_THEME_BADGE_SHAPE_CIRCLE")]
    PageThemeBadgeShapeCircle,
    #[serde(rename = "PAGE_THEME_BADGE_SHAPE_SQUARE")]
    PageThemeBadgeShapeSquare,
    #[serde(rename = "PAGE_THEME_BADGE_SHAPE_ROUNDED")]
    PageThemeBadgeShapeRounded,

}

impl std::fmt::Display for PageThemeBadgeShape {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::PageThemeBadgeShapeUnspecified => write!(f, "PAGE_THEME_BADGE_SHAPE_UNSPECIFIED"),
            Self::PageThemeBadgeShapeCircle => write!(f, "PAGE_THEME_BADGE_SHAPE_CIRCLE"),
            Self::PageThemeBadgeShapeSquare => write!(f, "PAGE_THEME_BADGE_SHAPE_SQUARE"),
            Self::PageThemeBadgeShapeRounded => write!(f, "PAGE_THEME_BADGE_SHAPE_ROUNDED"),
        }
    }
}

impl Default for PageThemeBadgeShape {
    fn default() -> PageThemeBadgeShape {
        Self::PageThemeBadgeShapeUnspecified
    }
}

