/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.43.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PasswordTraceData : PasswordTraceData stores password step validation results.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PasswordTraceData {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "validated", skip_serializing_if = "Option::is_none")]
    pub validated: Option<bool>,
}

impl PasswordTraceData {
    /// PasswordTraceData stores password step validation results.
    pub fn new() -> PasswordTraceData {
        PasswordTraceData {
            description: None,
            title: None,
            validated: None,
        }
    }
}

