/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.148.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PlanLimitKey : - PLAN_LIMIT_KEY_UNSPECIFIED: Not set  - PLAN_LIMIT_KEY_CUSTOM_DOMAINS: Custom domains connected to the workspace  - PLAN_LIMIT_KEY_TEAM_MEMBERS: Members of the workspace  - PLAN_LIMIT_KEY_PLATFORM_CREDITS: Platform credits, spent by creating links and by AI features  - PLAN_LIMIT_KEY_TRACKED_VISITS: Tracked visits (scans and clicks)  - PLAN_LIMIT_KEY_PUBLIC_API_CALLS: Public API calls  - PLAN_LIMIT_KEY_WEBHOOKS: Webhooks configured in the workspace  - PLAN_LIMIT_KEY_ASSISTANT_MESSAGES_PER_MINUTE: Assistant messages per minute  - PLAN_LIMIT_KEY_LINKS_INCLUDED: Links the monthly platform credits pay for. Links are not capped on their own: each one spends credits.
/// - PLAN_LIMIT_KEY_UNSPECIFIED: Not set  - PLAN_LIMIT_KEY_CUSTOM_DOMAINS: Custom domains connected to the workspace  - PLAN_LIMIT_KEY_TEAM_MEMBERS: Members of the workspace  - PLAN_LIMIT_KEY_PLATFORM_CREDITS: Platform credits, spent by creating links and by AI features  - PLAN_LIMIT_KEY_TRACKED_VISITS: Tracked visits (scans and clicks)  - PLAN_LIMIT_KEY_PUBLIC_API_CALLS: Public API calls  - PLAN_LIMIT_KEY_WEBHOOKS: Webhooks configured in the workspace  - PLAN_LIMIT_KEY_ASSISTANT_MESSAGES_PER_MINUTE: Assistant messages per minute  - PLAN_LIMIT_KEY_LINKS_INCLUDED: Links the monthly platform credits pay for. Links are not capped on their own: each one spends credits.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PlanLimitKey {
    #[serde(rename = "PLAN_LIMIT_KEY_UNSPECIFIED")]
    PlanLimitKeyUnspecified,
    #[serde(rename = "PLAN_LIMIT_KEY_CUSTOM_DOMAINS")]
    PlanLimitKeyCustomDomains,
    #[serde(rename = "PLAN_LIMIT_KEY_TEAM_MEMBERS")]
    PlanLimitKeyTeamMembers,
    #[serde(rename = "PLAN_LIMIT_KEY_PLATFORM_CREDITS")]
    PlanLimitKeyPlatformCredits,
    #[serde(rename = "PLAN_LIMIT_KEY_TRACKED_VISITS")]
    PlanLimitKeyTrackedVisits,
    #[serde(rename = "PLAN_LIMIT_KEY_PUBLIC_API_CALLS")]
    PlanLimitKeyPublicApiCalls,
    #[serde(rename = "PLAN_LIMIT_KEY_WEBHOOKS")]
    PlanLimitKeyWebhooks,
    #[serde(rename = "PLAN_LIMIT_KEY_ASSISTANT_MESSAGES_PER_MINUTE")]
    PlanLimitKeyAssistantMessagesPerMinute,
    #[serde(rename = "PLAN_LIMIT_KEY_LINKS_INCLUDED")]
    PlanLimitKeyLinksIncluded,

}

impl std::fmt::Display for PlanLimitKey {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::PlanLimitKeyUnspecified => write!(f, "PLAN_LIMIT_KEY_UNSPECIFIED"),
            Self::PlanLimitKeyCustomDomains => write!(f, "PLAN_LIMIT_KEY_CUSTOM_DOMAINS"),
            Self::PlanLimitKeyTeamMembers => write!(f, "PLAN_LIMIT_KEY_TEAM_MEMBERS"),
            Self::PlanLimitKeyPlatformCredits => write!(f, "PLAN_LIMIT_KEY_PLATFORM_CREDITS"),
            Self::PlanLimitKeyTrackedVisits => write!(f, "PLAN_LIMIT_KEY_TRACKED_VISITS"),
            Self::PlanLimitKeyPublicApiCalls => write!(f, "PLAN_LIMIT_KEY_PUBLIC_API_CALLS"),
            Self::PlanLimitKeyWebhooks => write!(f, "PLAN_LIMIT_KEY_WEBHOOKS"),
            Self::PlanLimitKeyAssistantMessagesPerMinute => write!(f, "PLAN_LIMIT_KEY_ASSISTANT_MESSAGES_PER_MINUTE"),
            Self::PlanLimitKeyLinksIncluded => write!(f, "PLAN_LIMIT_KEY_LINKS_INCLUDED"),
        }
    }
}

impl Default for PlanLimitKey {
    fn default() -> PlanLimitKey {
        Self::PlanLimitKeyUnspecified
    }
}

