/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.148.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlanTrial {
    #[serde(rename = "days", skip_serializing_if = "Option::is_none")]
    pub days: Option<i32>,
    /// What a workspace on the trial is allowed. Mostly the plan's limits, with the exceptions enforcement makes.
    #[serde(rename = "limits", skip_serializing_if = "Option::is_none")]
    pub limits: Option<Vec<models::PlanLimit>>,
    #[serde(rename = "signupOffer", skip_serializing_if = "Option::is_none")]
    pub signup_offer: Option<String>,
    #[serde(rename = "signupUrl", skip_serializing_if = "Option::is_none")]
    pub signup_url: Option<String>,
}

impl PlanTrial {
    pub fn new() -> PlanTrial {
        PlanTrial {
            days: None,
            limits: None,
            signup_offer: None,
            signup_url: None,
        }
    }
}

