/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.146.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlanPrice {
    #[serde(rename = "amounts", skip_serializing_if = "Option::is_none")]
    pub amounts: Option<Vec<models::Money>>,
    #[serde(rename = "interval", skip_serializing_if = "Option::is_none")]
    pub interval: Option<models::BillingInterval>,
    /// The charge spread over one month, one entry per currency. Equals amounts for a monthly price.
    #[serde(rename = "monthlyEquivalents", skip_serializing_if = "Option::is_none")]
    pub monthly_equivalents: Option<Vec<models::Money>>,
}

impl PlanPrice {
    pub fn new() -> PlanPrice {
        PlanPrice {
            amounts: None,
            interval: None,
            monthly_equivalents: None,
        }
    }
}

