/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.146.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PlanLimitKind : - PLAN_LIMIT_KIND_UNSPECIFIED: Not set  - PLAN_LIMIT_KIND_TOTAL: A standing total that does not refill, such as connected domains  - PLAN_LIMIT_KIND_MONTHLY: An allowance that refills every month  - PLAN_LIMIT_KIND_PER_MINUTE: A rate that refills every minute  - PLAN_LIMIT_KIND_UNLIMITED: No ceiling  - PLAN_LIMIT_KIND_METERED: No ceiling; every unit is billed
/// - PLAN_LIMIT_KIND_UNSPECIFIED: Not set  - PLAN_LIMIT_KIND_TOTAL: A standing total that does not refill, such as connected domains  - PLAN_LIMIT_KIND_MONTHLY: An allowance that refills every month  - PLAN_LIMIT_KIND_PER_MINUTE: A rate that refills every minute  - PLAN_LIMIT_KIND_UNLIMITED: No ceiling  - PLAN_LIMIT_KIND_METERED: No ceiling; every unit is billed
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PlanLimitKind {
    #[serde(rename = "PLAN_LIMIT_KIND_UNSPECIFIED")]
    PlanLimitKindUnspecified,
    #[serde(rename = "PLAN_LIMIT_KIND_TOTAL")]
    PlanLimitKindTotal,
    #[serde(rename = "PLAN_LIMIT_KIND_MONTHLY")]
    PlanLimitKindMonthly,
    #[serde(rename = "PLAN_LIMIT_KIND_PER_MINUTE")]
    PlanLimitKindPerMinute,
    #[serde(rename = "PLAN_LIMIT_KIND_UNLIMITED")]
    PlanLimitKindUnlimited,
    #[serde(rename = "PLAN_LIMIT_KIND_METERED")]
    PlanLimitKindMetered,

}

impl std::fmt::Display for PlanLimitKind {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::PlanLimitKindUnspecified => write!(f, "PLAN_LIMIT_KIND_UNSPECIFIED"),
            Self::PlanLimitKindTotal => write!(f, "PLAN_LIMIT_KIND_TOTAL"),
            Self::PlanLimitKindMonthly => write!(f, "PLAN_LIMIT_KIND_MONTHLY"),
            Self::PlanLimitKindPerMinute => write!(f, "PLAN_LIMIT_KIND_PER_MINUTE"),
            Self::PlanLimitKindUnlimited => write!(f, "PLAN_LIMIT_KIND_UNLIMITED"),
            Self::PlanLimitKindMetered => write!(f, "PLAN_LIMIT_KIND_METERED"),
        }
    }
}

impl Default for PlanLimitKind {
    fn default() -> PlanLimitKind {
        Self::PlanLimitKindUnspecified
    }
}

