/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.7
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PreferredLinkType : PreferredLinkType indicates the dominant link creation pattern for a workspace.   - PREFERRED_LINK_TYPE_URL: Default when no links exist yet — treated as URL  - PREFERRED_LINK_TYPE_CONTACT_CARD: Workspace primarily creates contact card links  - PREFERRED_LINK_TYPE_SOCIAL_LINKS_PAGE: Workspace primarily creates social links pages  - PREFERRED_LINK_TYPE_MIX: Workspace uses a mix of different link types
/// PreferredLinkType indicates the dominant link creation pattern for a workspace.   - PREFERRED_LINK_TYPE_URL: Default when no links exist yet — treated as URL  - PREFERRED_LINK_TYPE_CONTACT_CARD: Workspace primarily creates contact card links  - PREFERRED_LINK_TYPE_SOCIAL_LINKS_PAGE: Workspace primarily creates social links pages  - PREFERRED_LINK_TYPE_MIX: Workspace uses a mix of different link types
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PreferredLinkType {
    #[serde(rename = "PREFERRED_LINK_TYPE_URL")]
    PreferredLinkTypeUrl,
    #[serde(rename = "PREFERRED_LINK_TYPE_CONTACT_CARD")]
    PreferredLinkTypeContactCard,
    #[serde(rename = "PREFERRED_LINK_TYPE_SOCIAL_LINKS_PAGE")]
    PreferredLinkTypeSocialLinksPage,
    #[serde(rename = "PREFERRED_LINK_TYPE_MIX")]
    PreferredLinkTypeMix,

}

impl std::fmt::Display for PreferredLinkType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::PreferredLinkTypeUrl => write!(f, "PREFERRED_LINK_TYPE_URL"),
            Self::PreferredLinkTypeContactCard => write!(f, "PREFERRED_LINK_TYPE_CONTACT_CARD"),
            Self::PreferredLinkTypeSocialLinksPage => write!(f, "PREFERRED_LINK_TYPE_SOCIAL_LINKS_PAGE"),
            Self::PreferredLinkTypeMix => write!(f, "PREFERRED_LINK_TYPE_MIX"),
        }
    }
}

impl Default for PreferredLinkType {
    fn default() -> PreferredLinkType {
        Self::PreferredLinkTypeUrl
    }
}

