/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.148.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PricingPlanId : - PRICING_PLAN_ID_UNSPECIFIED: Not set  - PRICING_PLAN_ID_FREE: Free plan, no payment  - PRICING_PLAN_ID_LIGHT: Light plan  - PRICING_PLAN_ID_PRO: Pro plan. Trials and sponsored workspaces are allowed what Pro allows unless a limit says otherwise.  - PRICING_PLAN_ID_ENTERPRISE: Enterprise plan, billed per unit used
/// - PRICING_PLAN_ID_UNSPECIFIED: Not set  - PRICING_PLAN_ID_FREE: Free plan, no payment  - PRICING_PLAN_ID_LIGHT: Light plan  - PRICING_PLAN_ID_PRO: Pro plan. Trials and sponsored workspaces are allowed what Pro allows unless a limit says otherwise.  - PRICING_PLAN_ID_ENTERPRISE: Enterprise plan, billed per unit used
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PricingPlanId {
    #[serde(rename = "PRICING_PLAN_ID_UNSPECIFIED")]
    PricingPlanIdUnspecified,
    #[serde(rename = "PRICING_PLAN_ID_FREE")]
    PricingPlanIdFree,
    #[serde(rename = "PRICING_PLAN_ID_LIGHT")]
    PricingPlanIdLight,
    #[serde(rename = "PRICING_PLAN_ID_PRO")]
    PricingPlanIdPro,
    #[serde(rename = "PRICING_PLAN_ID_ENTERPRISE")]
    PricingPlanIdEnterprise,

}

impl std::fmt::Display for PricingPlanId {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::PricingPlanIdUnspecified => write!(f, "PRICING_PLAN_ID_UNSPECIFIED"),
            Self::PricingPlanIdFree => write!(f, "PRICING_PLAN_ID_FREE"),
            Self::PricingPlanIdLight => write!(f, "PRICING_PLAN_ID_LIGHT"),
            Self::PricingPlanIdPro => write!(f, "PRICING_PLAN_ID_PRO"),
            Self::PricingPlanIdEnterprise => write!(f, "PRICING_PLAN_ID_ENTERPRISE"),
        }
    }
}

impl Default for PricingPlanId {
    fn default() -> PricingPlanId {
        Self::PricingPlanIdUnspecified
    }
}

