/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.126.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicListPageThemeTemplatesResponse {
    #[serde(rename = "hasMore", skip_serializing_if = "Option::is_none")]
    pub has_more: Option<bool>,
    #[serde(rename = "nextPageToken", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
    #[serde(rename = "pageThemeTemplates", skip_serializing_if = "Option::is_none")]
    pub page_theme_templates: Option<Vec<models::PublicPageThemeTemplate>>,
}

impl PublicListPageThemeTemplatesResponse {
    pub fn new() -> PublicListPageThemeTemplatesResponse {
        PublicListPageThemeTemplatesResponse {
            has_more: None,
            next_page_token: None,
            page_theme_templates: None,
        }
    }
}

