/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.13
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicListQrcodeTemplatesResponse {
    #[serde(rename = "hasMore", skip_serializing_if = "Option::is_none")]
    pub has_more: Option<bool>,
    /// Cursor token returned when another page is available
    #[serde(rename = "nextPageToken", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
    #[serde(rename = "qrcodeTemplates", skip_serializing_if = "Option::is_none")]
    pub qrcode_templates: Option<Vec<models::PublicQrcodeTemplate>>,
}

impl PublicListQrcodeTemplatesResponse {
    pub fn new() -> PublicListQrcodeTemplatesResponse {
        PublicListQrcodeTemplatesResponse {
            has_more: None,
            next_page_token: None,
            qrcode_templates: None,
        }
    }
}

