/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.43.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublishQrcodeTemplateResponse {
    #[serde(rename = "qrcodeTemplate", skip_serializing_if = "Option::is_none")]
    pub qrcode_template: Option<Box<models::QrcodeTemplate>>,
}

impl PublishQrcodeTemplateResponse {
    pub fn new() -> PublishQrcodeTemplateResponse {
        PublishQrcodeTemplateResponse {
            qrcode_template: None,
        }
    }
}

