/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.125.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublishPageThemeTemplateResponse {
    #[serde(rename = "pageThemeTemplate", skip_serializing_if = "Option::is_none")]
    pub page_theme_template: Option<Box<models::PageThemeTemplate>>,
}

impl PublishPageThemeTemplateResponse {
    pub fn new() -> PublishPageThemeTemplateResponse {
        PublishPageThemeTemplateResponse {
            page_theme_template: None,
        }
    }
}

