/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.45.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QrcodeTemplatesServiceUpdateQrcodeTemplateBody {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "faq", skip_serializing_if = "Option::is_none")]
    pub faq: Option<String>,
    /// Extended markdown-supported content providing detailed information about the template
    #[serde(rename = "learnMore", skip_serializing_if = "Option::is_none")]
    pub learn_more: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<String>,
}

impl QrcodeTemplatesServiceUpdateQrcodeTemplateBody {
    pub fn new() -> QrcodeTemplatesServiceUpdateQrcodeTemplateBody {
        QrcodeTemplatesServiceUpdateQrcodeTemplateBody {
            description: None,
            faq: None,
            learn_more: None,
            name: None,
            slug: None,
            tags: None,
        }
    }
}

