/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.44.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RequestWorkspaceEnrollmentRequest {
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl RequestWorkspaceEnrollmentRequest {
    pub fn new() -> RequestWorkspaceEnrollmentRequest {
        RequestWorkspaceEnrollmentRequest {
            message: None,
        }
    }
}

