/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.135.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ResolveQrcodeTemplateImagesResponse : ResolveQrcodeTemplateImagesResponse carries the resolved thumbnails.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResolveQrcodeTemplateImagesResponse {
    /// Signed thumbnail URL by template id. These expire; fetch rather than store.
    #[serde(rename = "thumbnailSignedUrls", skip_serializing_if = "Option::is_none")]
    pub thumbnail_signed_urls: Option<std::collections::HashMap<String, String>>,
}

impl ResolveQrcodeTemplateImagesResponse {
    /// ResolveQrcodeTemplateImagesResponse carries the resolved thumbnails.
    pub fn new() -> ResolveQrcodeTemplateImagesResponse {
        ResolveQrcodeTemplateImagesResponse {
            thumbnail_signed_urls: None,
        }
    }
}

