/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.140.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ResolvePageThemeTemplateImagesResponse : ResolvePageThemeTemplateImagesResponse carries the resolved images.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResolvePageThemeTemplateImagesResponse {
    /// Images by template id. These expire; fetch rather than store.
    #[serde(rename = "images", skip_serializing_if = "Option::is_none")]
    pub images: Option<std::collections::HashMap<String, models::PageThemeTemplateImages>>,
}

impl ResolvePageThemeTemplateImagesResponse {
    /// ResolvePageThemeTemplateImagesResponse carries the resolved images.
    pub fn new() -> ResolvePageThemeTemplateImagesResponse {
        ResolvePageThemeTemplateImagesResponse {
            images: None,
        }
    }
}

