/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.44.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SettingsServiceUpdateLinkSettingBody : UpdateLinkSettingRequest changes the visitor-data policy tied to a specific link.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SettingsServiceUpdateLinkSettingBody {
    #[serde(rename = "dataCollection", skip_serializing_if = "Option::is_none")]
    pub data_collection: Option<models::DataCollection>,
}

impl SettingsServiceUpdateLinkSettingBody {
    /// UpdateLinkSettingRequest changes the visitor-data policy tied to a specific link.
    pub fn new() -> SettingsServiceUpdateLinkSettingBody {
        SettingsServiceUpdateLinkSettingBody {
            data_collection: None,
        }
    }
}

