/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.53.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SlackIntegrationStatus : - SLACK_INTEGRATION_STATUS_UNSPECIFIED: Status not specified  - SLACK_INTEGRATION_STATUS_ACTIVE: Integration is active and sending notifications  - SLACK_INTEGRATION_STATUS_PAUSED: Integration is paused by user action  - SLACK_INTEGRATION_STATUS_DISCONNECTED: Integration is disconnected
/// - SLACK_INTEGRATION_STATUS_UNSPECIFIED: Status not specified  - SLACK_INTEGRATION_STATUS_ACTIVE: Integration is active and sending notifications  - SLACK_INTEGRATION_STATUS_PAUSED: Integration is paused by user action  - SLACK_INTEGRATION_STATUS_DISCONNECTED: Integration is disconnected
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SlackIntegrationStatus {
    #[serde(rename = "SLACK_INTEGRATION_STATUS_UNSPECIFIED")]
    SlackIntegrationStatusUnspecified,
    #[serde(rename = "SLACK_INTEGRATION_STATUS_ACTIVE")]
    SlackIntegrationStatusActive,
    #[serde(rename = "SLACK_INTEGRATION_STATUS_PAUSED")]
    SlackIntegrationStatusPaused,
    #[serde(rename = "SLACK_INTEGRATION_STATUS_DISCONNECTED")]
    SlackIntegrationStatusDisconnected,

}

impl std::fmt::Display for SlackIntegrationStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::SlackIntegrationStatusUnspecified => write!(f, "SLACK_INTEGRATION_STATUS_UNSPECIFIED"),
            Self::SlackIntegrationStatusActive => write!(f, "SLACK_INTEGRATION_STATUS_ACTIVE"),
            Self::SlackIntegrationStatusPaused => write!(f, "SLACK_INTEGRATION_STATUS_PAUSED"),
            Self::SlackIntegrationStatusDisconnected => write!(f, "SLACK_INTEGRATION_STATUS_DISCONNECTED"),
        }
    }
}

impl Default for SlackIntegrationStatus {
    fn default() -> SlackIntegrationStatus {
        Self::SlackIntegrationStatusUnspecified
    }
}

