/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SocialLinksTraceData : SocialLinksTraceData stores social links page interaction details.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SocialLinksTraceData {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "displayStyle", skip_serializing_if = "Option::is_none")]
    pub display_style: Option<String>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Vec<models::SocialLinkTraceButton>>,
    #[serde(rename = "selectedLink", skip_serializing_if = "Option::is_none")]
    pub selected_link: Option<Box<models::SocialLinkTraceButton>>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
}

impl SocialLinksTraceData {
    /// SocialLinksTraceData stores social links page interaction details.
    pub fn new() -> SocialLinksTraceData {
        SocialLinksTraceData {
            description: None,
            display_style: None,
            links: None,
            selected_link: None,
            title: None,
        }
    }
}

