/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SocialLinksPayload {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "displayStyle", skip_serializing_if = "Option::is_none")]
    pub display_style: Option<models::SocialLinksDisplayStyle>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Vec<models::SocialLinkButton>>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
}

impl SocialLinksPayload {
    pub fn new() -> SocialLinksPayload {
        SocialLinksPayload {
            description: None,
            display_style: None,
            links: None,
            title: None,
        }
    }
}

