/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.132.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SocketUnsubscribeRequest : SocketUnsubscribeRequest leaves a channel.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SocketUnsubscribeRequest {
    #[serde(rename = "channel", skip_serializing_if = "Option::is_none")]
    pub channel: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::SocketMessageType>,
}

impl SocketUnsubscribeRequest {
    /// SocketUnsubscribeRequest leaves a channel.
    pub fn new() -> SocketUnsubscribeRequest {
        SocketUnsubscribeRequest {
            channel: None,
            r#type: None,
        }
    }
}

