/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.131.10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SocketConnectedMessage : SocketConnectedMessage confirms the socket is authenticated.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SocketConnectedMessage {
    #[serde(rename = "memberId", skip_serializing_if = "Option::is_none")]
    pub member_id: Option<String>,
    #[serde(rename = "sessionId", skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::SocketMessageType>,
    #[serde(rename = "workspaceId", skip_serializing_if = "Option::is_none")]
    pub workspace_id: Option<String>,
}

impl SocketConnectedMessage {
    /// SocketConnectedMessage confirms the socket is authenticated.
    pub fn new() -> SocketConnectedMessage {
        SocketConnectedMessage {
            member_id: None,
            session_id: None,
            r#type: None,
            workspace_id: None,
        }
    }
}

