/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.128.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SocketAgentSendRequest : SocketAgentSendRequest asks the agent for a reply.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SocketAgentSendRequest {
    #[serde(rename = "contextId", skip_serializing_if = "Option::is_none")]
    pub context_id: Option<String>,
    /// Whatever the page knows and the agent cannot see.
    #[serde(rename = "contextMetadata", skip_serializing_if = "Option::is_none")]
    pub context_metadata: Option<String>,
    #[serde(rename = "contextType", skip_serializing_if = "Option::is_none")]
    pub context_type: Option<String>,
    /// Files already uploaded, to attach to this turn.
    #[serde(rename = "fileIds", skip_serializing_if = "Option::is_none")]
    pub file_ids: Option<Vec<String>>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// Correlates the reply to this message. The client generates it.
    #[serde(rename = "requestId", skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::SocketMessageType>,
}

impl SocketAgentSendRequest {
    /// SocketAgentSendRequest asks the agent for a reply.
    pub fn new() -> SocketAgentSendRequest {
        SocketAgentSendRequest {
            context_id: None,
            context_metadata: None,
            context_type: None,
            file_ids: None,
            message: None,
            request_id: None,
            r#type: None,
        }
    }
}

