/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.131.11
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SocketErrorCode : SocketErrorCode is why a request could not be served.   - SOCKET_ERROR_CODE_FORBIDDEN: The caller asked for something outside their workspace.
/// SocketErrorCode is why a request could not be served.   - SOCKET_ERROR_CODE_FORBIDDEN: The caller asked for something outside their workspace.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SocketErrorCode {
    #[serde(rename = "SOCKET_ERROR_CODE_UNSPECIFIED")]
    SocketErrorCodeUnspecified,
    #[serde(rename = "SOCKET_ERROR_CODE_RATE_LIMITED")]
    SocketErrorCodeRateLimited,
    #[serde(rename = "SOCKET_ERROR_CODE_CREDITS_EXHAUSTED")]
    SocketErrorCodeCreditsExhausted,
    #[serde(rename = "SOCKET_ERROR_CODE_WORKSPACE_NOT_VERIFIED")]
    SocketErrorCodeWorkspaceNotVerified,
    #[serde(rename = "SOCKET_ERROR_CODE_BUSY")]
    SocketErrorCodeBusy,
    #[serde(rename = "SOCKET_ERROR_CODE_INVALID_CONTEXT")]
    SocketErrorCodeInvalidContext,
    #[serde(rename = "SOCKET_ERROR_CODE_INTERNAL_ERROR")]
    SocketErrorCodeInternalError,
    #[serde(rename = "SOCKET_ERROR_CODE_FORBIDDEN")]
    SocketErrorCodeForbidden,

}

impl std::fmt::Display for SocketErrorCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::SocketErrorCodeUnspecified => write!(f, "SOCKET_ERROR_CODE_UNSPECIFIED"),
            Self::SocketErrorCodeRateLimited => write!(f, "SOCKET_ERROR_CODE_RATE_LIMITED"),
            Self::SocketErrorCodeCreditsExhausted => write!(f, "SOCKET_ERROR_CODE_CREDITS_EXHAUSTED"),
            Self::SocketErrorCodeWorkspaceNotVerified => write!(f, "SOCKET_ERROR_CODE_WORKSPACE_NOT_VERIFIED"),
            Self::SocketErrorCodeBusy => write!(f, "SOCKET_ERROR_CODE_BUSY"),
            Self::SocketErrorCodeInvalidContext => write!(f, "SOCKET_ERROR_CODE_INVALID_CONTEXT"),
            Self::SocketErrorCodeInternalError => write!(f, "SOCKET_ERROR_CODE_INTERNAL_ERROR"),
            Self::SocketErrorCodeForbidden => write!(f, "SOCKET_ERROR_CODE_FORBIDDEN"),
        }
    }
}

impl Default for SocketErrorCode {
    fn default() -> SocketErrorCode {
        Self::SocketErrorCodeUnspecified
    }
}

