/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.134.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SocketAssistantErrorMessage : SocketAssistantErrorMessage says why there will be no reply.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SocketAssistantErrorMessage {
    #[serde(rename = "errorCode", skip_serializing_if = "Option::is_none")]
    pub error_code: Option<models::SocketErrorCode>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "requestId", skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::SocketMessageType>,
}

impl SocketAssistantErrorMessage {
    /// SocketAssistantErrorMessage says why there will be no reply.
    pub fn new() -> SocketAssistantErrorMessage {
        SocketAssistantErrorMessage {
            error_code: None,
            message: None,
            request_id: None,
            r#type: None,
        }
    }
}

