/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.129.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SocketSubscribeDeniedMessage : SocketSubscribeDeniedMessage refuses a channel the caller may not read.  Said out loud rather than dropped silently: a client that believes it is subscribed and receives nothing cannot tell that apart from a quiet channel.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SocketSubscribeDeniedMessage {
    #[serde(rename = "channel", skip_serializing_if = "Option::is_none")]
    pub channel: Option<String>,
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<models::SocketErrorCode>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::SocketMessageType>,
}

impl SocketSubscribeDeniedMessage {
    /// SocketSubscribeDeniedMessage refuses a channel the caller may not read.  Said out loud rather than dropped silently: a client that believes it is subscribed and receives nothing cannot tell that apart from a quiet channel.
    pub fn new() -> SocketSubscribeDeniedMessage {
        SocketSubscribeDeniedMessage {
            channel: None,
            code: None,
            message: None,
            r#type: None,
        }
    }
}

