/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.146.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SocketAssistantProgressMessage : SocketAssistantProgressMessage says what the assistant is doing while it works.  A reply can take a model several tool calls to produce. Without these the screen has nothing to show for that time.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SocketAssistantProgressMessage {
    #[serde(rename = "detail", skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
    #[serde(rename = "requestId", skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
    /// \"thinking\", \"calling_tool\", and so on.
    #[serde(rename = "step", skip_serializing_if = "Option::is_none")]
    pub step: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::SocketMessageType>,
}

impl SocketAssistantProgressMessage {
    /// SocketAssistantProgressMessage says what the assistant is doing while it works.  A reply can take a model several tool calls to produce. Without these the screen has nothing to show for that time.
    pub fn new() -> SocketAssistantProgressMessage {
        SocketAssistantProgressMessage {
            detail: None,
            request_id: None,
            step: None,
            r#type: None,
        }
    }
}

