/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.44.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SpecificDateConditionPayload {
    #[serde(rename = "elseNextStepId", skip_serializing_if = "Option::is_none")]
    pub else_next_step_id: Option<String>,
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Vec<models::SpecificDateOption>>,
}

impl SpecificDateConditionPayload {
    pub fn new() -> SpecificDateConditionPayload {
        SpecificDateConditionPayload {
            else_next_step_id: None,
            options: None,
        }
    }
}

