/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.90.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StepThemeOverride : Theme override for a specific workflow step. All fields are optional — only set fields override the global page theme when this step is displayed to visitors.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StepThemeOverride {
    #[serde(rename = "badgeEnabled", skip_serializing_if = "Option::is_none")]
    pub badge_enabled: Option<bool>,
    #[serde(rename = "badgeIconColor", skip_serializing_if = "Option::is_none")]
    pub badge_icon_color: Option<Box<models::ThemeColor>>,
    #[serde(rename = "badgeId", skip_serializing_if = "Option::is_none")]
    pub badge_id: Option<String>,
    #[serde(rename = "badgeShape", skip_serializing_if = "Option::is_none")]
    pub badge_shape: Option<BadgeShape>,
}

impl StepThemeOverride {
    /// Theme override for a specific workflow step. All fields are optional — only set fields override the global page theme when this step is displayed to visitors.
    pub fn new() -> StepThemeOverride {
        StepThemeOverride {
            badge_enabled: None,
            badge_icon_color: None,
            badge_id: None,
            badge_shape: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BadgeShape {
    #[serde(rename = "PAGE_THEME_BADGE_SHAPE_UNSPECIFIED")]
    PageThemeBadgeShapeUnspecified,
    #[serde(rename = "PAGE_THEME_BADGE_SHAPE_CIRCLE")]
    PageThemeBadgeShapeCircle,
    #[serde(rename = "PAGE_THEME_BADGE_SHAPE_SQUARE")]
    PageThemeBadgeShapeSquare,
    #[serde(rename = "PAGE_THEME_BADGE_SHAPE_ROUNDED")]
    PageThemeBadgeShapeRounded,
}

impl Default for BadgeShape {
    fn default() -> BadgeShape {
        Self::PageThemeBadgeShapeUnspecified
    }
}

