/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.44.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SubscriptionType : - SUBSCRIPTION_TYPE_UNSPECIFIED: Subscription plan not yet assigned  - SUBSCRIPTION_TYPE_FREE_TRIAL: Workspace is currently in the free trial period  - SUBSCRIPTION_TYPE_SPONSORED_PRO: Workspace is on the sponsored pro plan with full pro features  - SUBSCRIPTION_TYPE_PRO_PLAN: Workspace has an active Pro plan subscription  - SUBSCRIPTION_TYPE_ENTERPRISE_PLAN: Workspace is managed under an Enterprise contract  - SUBSCRIPTION_TYPE_LIGHT_PLAN: Workspace has an active Light plan subscription
/// - SUBSCRIPTION_TYPE_UNSPECIFIED: Subscription plan not yet assigned  - SUBSCRIPTION_TYPE_FREE_TRIAL: Workspace is currently in the free trial period  - SUBSCRIPTION_TYPE_SPONSORED_PRO: Workspace is on the sponsored pro plan with full pro features  - SUBSCRIPTION_TYPE_PRO_PLAN: Workspace has an active Pro plan subscription  - SUBSCRIPTION_TYPE_ENTERPRISE_PLAN: Workspace is managed under an Enterprise contract  - SUBSCRIPTION_TYPE_LIGHT_PLAN: Workspace has an active Light plan subscription
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SubscriptionType {
    #[serde(rename = "SUBSCRIPTION_TYPE_UNSPECIFIED")]
    SubscriptionTypeUnspecified,
    #[serde(rename = "SUBSCRIPTION_TYPE_FREE_TRIAL")]
    SubscriptionTypeFreeTrial,
    #[serde(rename = "SUBSCRIPTION_TYPE_SPONSORED_PRO")]
    SubscriptionTypeSponsoredPro,
    #[serde(rename = "SUBSCRIPTION_TYPE_PRO_PLAN")]
    SubscriptionTypeProPlan,
    #[serde(rename = "SUBSCRIPTION_TYPE_ENTERPRISE_PLAN")]
    SubscriptionTypeEnterprisePlan,
    #[serde(rename = "SUBSCRIPTION_TYPE_LIGHT_PLAN")]
    SubscriptionTypeLightPlan,

}

impl std::fmt::Display for SubscriptionType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::SubscriptionTypeUnspecified => write!(f, "SUBSCRIPTION_TYPE_UNSPECIFIED"),
            Self::SubscriptionTypeFreeTrial => write!(f, "SUBSCRIPTION_TYPE_FREE_TRIAL"),
            Self::SubscriptionTypeSponsoredPro => write!(f, "SUBSCRIPTION_TYPE_SPONSORED_PRO"),
            Self::SubscriptionTypeProPlan => write!(f, "SUBSCRIPTION_TYPE_PRO_PLAN"),
            Self::SubscriptionTypeEnterprisePlan => write!(f, "SUBSCRIPTION_TYPE_ENTERPRISE_PLAN"),
            Self::SubscriptionTypeLightPlan => write!(f, "SUBSCRIPTION_TYPE_LIGHT_PLAN"),
        }
    }
}

impl Default for SubscriptionType {
    fn default() -> SubscriptionType {
        Self::SubscriptionTypeUnspecified
    }
}

