/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.106.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ThankYouPagePayload {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "title")]
    pub title: String,
}

impl ThankYouPagePayload {
    pub fn new(title: String) -> ThankYouPagePayload {
        ThankYouPagePayload {
            description: None,
            title,
        }
    }
}

