/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.98.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimeSeriesSeries {
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "points", skip_serializing_if = "Option::is_none")]
    pub points: Option<Vec<models::TimeSeriesPoint>>,
}

impl TimeSeriesSeries {
    pub fn new() -> TimeSeriesSeries {
        TimeSeriesSeries {
            label: None,
            points: None,
        }
    }
}

