/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.101.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TopLinkDataPoint {
    #[serde(rename = "eventCount", skip_serializing_if = "Option::is_none")]
    pub event_count: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "shortlink", skip_serializing_if = "Option::is_none")]
    pub shortlink: Option<String>,
}

impl TopLinkDataPoint {
    pub fn new() -> TopLinkDataPoint {
        TopLinkDataPoint {
            event_count: None,
            name: None,
            shortlink: None,
        }
    }
}

