/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.45.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TriggeredBy : - TRIGGERED_BY_UNSPECIFIED: Trigger source not specified  - TRIGGERED_BY_VISITOR: Visitor initiated the scan (as opposed to system-generated)
/// - TRIGGERED_BY_UNSPECIFIED: Trigger source not specified  - TRIGGERED_BY_VISITOR: Visitor initiated the scan (as opposed to system-generated)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TriggeredBy {
    #[serde(rename = "TRIGGERED_BY_UNSPECIFIED")]
    TriggeredByUnspecified,
    #[serde(rename = "TRIGGERED_BY_VISITOR")]
    TriggeredByVisitor,

}

impl std::fmt::Display for TriggeredBy {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::TriggeredByUnspecified => write!(f, "TRIGGERED_BY_UNSPECIFIED"),
            Self::TriggeredByVisitor => write!(f, "TRIGGERED_BY_VISITOR"),
        }
    }
}

impl Default for TriggeredBy {
    fn default() -> TriggeredBy {
        Self::TriggeredByUnspecified
    }
}

