/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateWorkspaceOriginPurposeRequest {
    #[serde(rename = "originPurpose", skip_serializing_if = "Option::is_none")]
    pub origin_purpose: Option<String>,
}

impl UpdateWorkspaceOriginPurposeRequest {
    pub fn new() -> UpdateWorkspaceOriginPurposeRequest {
        UpdateWorkspaceOriginPurposeRequest {
            origin_purpose: None,
        }
    }
}

