/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.125.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdatePageThemeTemplateStylingResponse : UpdatePageThemeTemplateStylingResponse returns the template with its updated theme.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdatePageThemeTemplateStylingResponse {
    #[serde(rename = "pageThemeTemplate", skip_serializing_if = "Option::is_none")]
    pub page_theme_template: Option<Box<models::PageThemeTemplate>>,
}

impl UpdatePageThemeTemplateStylingResponse {
    /// UpdatePageThemeTemplateStylingResponse returns the template with its updated theme.
    pub fn new() -> UpdatePageThemeTemplateStylingResponse {
        UpdatePageThemeTemplateStylingResponse {
            page_theme_template: None,
        }
    }
}

