/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.9
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateWorkspaceRequest {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "enforceMfa", skip_serializing_if = "Option::is_none")]
    pub enforce_mfa: Option<bool>,
    #[serde(rename = "faq", skip_serializing_if = "Option::is_none")]
    pub faq: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "shortDescription", skip_serializing_if = "Option::is_none")]
    pub short_description: Option<String>,
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<String>,
    #[serde(rename = "website", skip_serializing_if = "Option::is_none")]
    pub website: Option<String>,
}

impl UpdateWorkspaceRequest {
    pub fn new() -> UpdateWorkspaceRequest {
        UpdateWorkspaceRequest {
            description: None,
            enforce_mfa: None,
            faq: None,
            name: None,
            short_description: None,
            slug: None,
            tags: None,
            website: None,
        }
    }
}

