/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.111.19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VCardSocialLink {
    /// Platform identifier picking the icon. Leave it empty and the API names it from the URL, which is what you normally want. Known values: appstore, playstore, instagram, tiktok, twitter, facebook, youtube, linkedin, github, medium, whatsapp, telegram, discord, slack, spotify, applemusic, twitch, snapchat, pinterest, reddit, calendly, website.
    #[serde(rename = "platform", skip_serializing_if = "Option::is_none")]
    pub platform: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl VCardSocialLink {
    pub fn new() -> VCardSocialLink {
        VCardSocialLink {
            platform: None,
            url: None,
        }
    }
}

