/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.118.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ValidationPurpose : - PURPOSE_UNSPECIFIED: Purpose not specified  - PURPOSE_OWNERSHIP: DNS record proves ownership of the domain  - PURPOSE_DOMAIN_VERIFICATION: DNS record enables TLS/domain verification with the provider  - PURPOSE_DCV_DELEGATION: DNS record delegates certificate validation to the provider so every future renewal validates automatically without a new record
/// - PURPOSE_UNSPECIFIED: Purpose not specified  - PURPOSE_OWNERSHIP: DNS record proves ownership of the domain  - PURPOSE_DOMAIN_VERIFICATION: DNS record enables TLS/domain verification with the provider  - PURPOSE_DCV_DELEGATION: DNS record delegates certificate validation to the provider so every future renewal validates automatically without a new record
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ValidationPurpose {
    #[serde(rename = "PURPOSE_UNSPECIFIED")]
    PurposeUnspecified,
    #[serde(rename = "PURPOSE_OWNERSHIP")]
    PurposeOwnership,
    #[serde(rename = "PURPOSE_DOMAIN_VERIFICATION")]
    PurposeDomainVerification,
    #[serde(rename = "PURPOSE_DCV_DELEGATION")]
    PurposeDcvDelegation,

}

impl std::fmt::Display for ValidationPurpose {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::PurposeUnspecified => write!(f, "PURPOSE_UNSPECIFIED"),
            Self::PurposeOwnership => write!(f, "PURPOSE_OWNERSHIP"),
            Self::PurposeDomainVerification => write!(f, "PURPOSE_DOMAIN_VERIFICATION"),
            Self::PurposeDcvDelegation => write!(f, "PURPOSE_DCV_DELEGATION"),
        }
    }
}

impl Default for ValidationPurpose {
    fn default() -> ValidationPurpose {
        Self::PurposeUnspecified
    }
}

