/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VisitTypeConditionTraceData : VisitTypeConditionTraceData stores visit type condition routing metadata.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VisitTypeConditionTraceData {
    #[serde(rename = "hasElse", skip_serializing_if = "Option::is_none")]
    pub has_else: Option<bool>,
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Vec<models::VisitTypeConditionTraceOption>>,
    #[serde(rename = "visitType", skip_serializing_if = "Option::is_none")]
    pub visit_type: Option<String>,
}

impl VisitTypeConditionTraceData {
    /// VisitTypeConditionTraceData stores visit type condition routing metadata.
    pub fn new() -> VisitTypeConditionTraceData {
        VisitTypeConditionTraceData {
            has_else: None,
            options: None,
            visit_type: None,
        }
    }
}

