/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.13
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VisitorDataConditionTraceData : VisitorDataConditionTraceData stores visitor-data routing metadata.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VisitorDataConditionTraceData {
    #[serde(rename = "hasElse", skip_serializing_if = "Option::is_none")]
    pub has_else: Option<bool>,
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Vec<models::VisitorDataConditionTraceOption>>,
}

impl VisitorDataConditionTraceData {
    /// VisitorDataConditionTraceData stores visitor-data routing metadata.
    pub fn new() -> VisitorDataConditionTraceData {
        VisitorDataConditionTraceData {
            has_else: None,
            options: None,
        }
    }
}

