/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.7
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookStatus : - WEBHOOK_STATUS_UNSPECIFIED: Webhook status not specified  - WEBHOOK_STATUS_ACTIVE: Webhook is active and receiving events  - WEBHOOK_STATUS_DISABLED: Webhook is disabled due to repeated failures  - WEBHOOK_STATUS_PAUSED: Webhook is paused by user action
/// - WEBHOOK_STATUS_UNSPECIFIED: Webhook status not specified  - WEBHOOK_STATUS_ACTIVE: Webhook is active and receiving events  - WEBHOOK_STATUS_DISABLED: Webhook is disabled due to repeated failures  - WEBHOOK_STATUS_PAUSED: Webhook is paused by user action
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WebhookStatus {
    #[serde(rename = "WEBHOOK_STATUS_UNSPECIFIED")]
    WebhookStatusUnspecified,
    #[serde(rename = "WEBHOOK_STATUS_ACTIVE")]
    WebhookStatusActive,
    #[serde(rename = "WEBHOOK_STATUS_DISABLED")]
    WebhookStatusDisabled,
    #[serde(rename = "WEBHOOK_STATUS_PAUSED")]
    WebhookStatusPaused,

}

impl std::fmt::Display for WebhookStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::WebhookStatusUnspecified => write!(f, "WEBHOOK_STATUS_UNSPECIFIED"),
            Self::WebhookStatusActive => write!(f, "WEBHOOK_STATUS_ACTIVE"),
            Self::WebhookStatusDisabled => write!(f, "WEBHOOK_STATUS_DISABLED"),
            Self::WebhookStatusPaused => write!(f, "WEBHOOK_STATUS_PAUSED"),
        }
    }
}

impl Default for WebhookStatus {
    fn default() -> WebhookStatus {
        Self::WebhookStatusUnspecified
    }
}

