/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.118.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WidgetTab {
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// How this tab produces its content. Absent means data.
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<models::WidgetTabMode>,
    #[serde(rename = "params", skip_serializing_if = "Option::is_none")]
    pub params: Option<serde_json::Value>,
    /// How it is drawn. The map used to be chosen by a tab literally labelled \"Map\", so renaming it to \"Carte\" lost the map and a data tab called \"Site Map clicks\" was hijacked into one.
    #[serde(rename = "view", skip_serializing_if = "Option::is_none")]
    pub view: Option<models::WidgetTabView>,
}

impl WidgetTab {
    pub fn new() -> WidgetTab {
        WidgetTab {
            label: None,
            mode: None,
            params: None,
            view: None,
        }
    }
}

