/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.118.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WidgetTabMode : WidgetTabMode says how a tab produces what it shows.   - WIDGET_TAB_MODE_UNSPECIFIED: Fetches the widget's data source with this tab's params, on switch.  - WIDGET_TAB_MODE_AGENT_SUMMARY: Shows an agent's analysis of the widget's values. Runs only when the user asks, because it costs platform credits, and its result is stored rather than regenerated on every view.
/// WidgetTabMode says how a tab produces what it shows.   - WIDGET_TAB_MODE_UNSPECIFIED: Fetches the widget's data source with this tab's params, on switch.  - WIDGET_TAB_MODE_AGENT_SUMMARY: Shows an agent's analysis of the widget's values. Runs only when the user asks, because it costs platform credits, and its result is stored rather than regenerated on every view.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WidgetTabMode {
    #[serde(rename = "WIDGET_TAB_MODE_UNSPECIFIED")]
    WidgetTabModeUnspecified,
    #[serde(rename = "WIDGET_TAB_MODE_DATA")]
    WidgetTabModeData,
    #[serde(rename = "WIDGET_TAB_MODE_AGENT_SUMMARY")]
    WidgetTabModeAgentSummary,

}

impl std::fmt::Display for WidgetTabMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::WidgetTabModeUnspecified => write!(f, "WIDGET_TAB_MODE_UNSPECIFIED"),
            Self::WidgetTabModeData => write!(f, "WIDGET_TAB_MODE_DATA"),
            Self::WidgetTabModeAgentSummary => write!(f, "WIDGET_TAB_MODE_AGENT_SUMMARY"),
        }
    }
}

impl Default for WidgetTabMode {
    fn default() -> WidgetTabMode {
        Self::WidgetTabModeUnspecified
    }
}

