/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.111.18
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WidgetTabView : WidgetTabView says how a tab draws what it fetched.   - WIDGET_TAB_VIEW_UNSPECIFIED: The widget's own chart type.  - WIDGET_TAB_VIEW_MAP: A world map, which needs rows carrying a country code.
/// WidgetTabView says how a tab draws what it fetched.   - WIDGET_TAB_VIEW_UNSPECIFIED: The widget's own chart type.  - WIDGET_TAB_VIEW_MAP: A world map, which needs rows carrying a country code.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WidgetTabView {
    #[serde(rename = "WIDGET_TAB_VIEW_UNSPECIFIED")]
    WidgetTabViewUnspecified,
    #[serde(rename = "WIDGET_TAB_VIEW_CHART")]
    WidgetTabViewChart,
    #[serde(rename = "WIDGET_TAB_VIEW_MAP")]
    WidgetTabViewMap,

}

impl std::fmt::Display for WidgetTabView {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::WidgetTabViewUnspecified => write!(f, "WIDGET_TAB_VIEW_UNSPECIFIED"),
            Self::WidgetTabViewChart => write!(f, "WIDGET_TAB_VIEW_CHART"),
            Self::WidgetTabViewMap => write!(f, "WIDGET_TAB_VIEW_MAP"),
        }
    }
}

impl Default for WidgetTabView {
    fn default() -> WidgetTabView {
        Self::WidgetTabViewUnspecified
    }
}

