/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.120.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkflowStepNodeType : The node type says how many exits a step has. Whatever the answer, you connect every one of them the same way, with workflow_steps_connect: name the branch, name the step it leads to. Read a step's branches field for its branch ids.  Example: a multi-link with 3 buttons has 3 branches, with the buttons' ids. A redirect has one branch, \"next\". A country condition has one branch per country plus \"else\".   - NODE_TYPE_UNSPECIFIED: Workflow step node type not specified  - NODE_TYPE_COMPOSITE: Composite steps have one exit per button, option or range, plus \"else\" for a condition's fallback. Examples: MULTI_LINK, VISIT_TYPE_CONDITION, COUNTRY_CONDITION, DAY_OF_WEEK_CONDITION, TIME_OF_DAY_CONDITION, DAY_OF_MONTH_CONDITION, SPECIFIC_DATE_CONDITION, DEVICE_*_CONDITION, VISITOR_DATA_CONDITION  - NODE_TYPE_ATOMIC: Atomic steps have exactly one exit, branch id \"next\". Exit steps (THANK_YOU_PAGE, CONTACT_CARD, SOCIAL_LINKS_PAGE, CLIENT_REDIRECT) are atomic but end the journey, so they have no branches at all. Examples: LINK_VISIT, PASSWORD_VERIFY, FORM_SUBMIT, MESSAGE_PAGE
/// The node type says how many exits a step has. Whatever the answer, you connect every one of them the same way, with workflow_steps_connect: name the branch, name the step it leads to. Read a step's branches field for its branch ids.  Example: a multi-link with 3 buttons has 3 branches, with the buttons' ids. A redirect has one branch, \"next\". A country condition has one branch per country plus \"else\".   - NODE_TYPE_UNSPECIFIED: Workflow step node type not specified  - NODE_TYPE_COMPOSITE: Composite steps have one exit per button, option or range, plus \"else\" for a condition's fallback. Examples: MULTI_LINK, VISIT_TYPE_CONDITION, COUNTRY_CONDITION, DAY_OF_WEEK_CONDITION, TIME_OF_DAY_CONDITION, DAY_OF_MONTH_CONDITION, SPECIFIC_DATE_CONDITION, DEVICE_*_CONDITION, VISITOR_DATA_CONDITION  - NODE_TYPE_ATOMIC: Atomic steps have exactly one exit, branch id \"next\". Exit steps (THANK_YOU_PAGE, CONTACT_CARD, SOCIAL_LINKS_PAGE, CLIENT_REDIRECT) are atomic but end the journey, so they have no branches at all. Examples: LINK_VISIT, PASSWORD_VERIFY, FORM_SUBMIT, MESSAGE_PAGE
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WorkflowStepNodeType {
    #[serde(rename = "NODE_TYPE_UNSPECIFIED")]
    NodeTypeUnspecified,
    #[serde(rename = "NODE_TYPE_COMPOSITE")]
    NodeTypeComposite,
    #[serde(rename = "NODE_TYPE_ATOMIC")]
    NodeTypeAtomic,

}

impl std::fmt::Display for WorkflowStepNodeType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::NodeTypeUnspecified => write!(f, "NODE_TYPE_UNSPECIFIED"),
            Self::NodeTypeComposite => write!(f, "NODE_TYPE_COMPOSITE"),
            Self::NodeTypeAtomic => write!(f, "NODE_TYPE_ATOMIC"),
        }
    }
}

impl Default for WorkflowStepNodeType {
    fn default() -> WorkflowStepNodeType {
        Self::NodeTypeUnspecified
    }
}

