/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowStepsServiceCreateBody {
    #[serde(rename = "canvasPosition", skip_serializing_if = "Option::is_none")]
    pub canvas_position: Option<Box<models::CanvasPosition>>,
    /// - EVENT_ACTION_UNSPECIFIED: Event action not specified  - EVENT_ACTION_CLIENT_REDIRECT: Redirect visitors to a destination URL  - EVENT_ACTION_LINK_VISIT: Entry step triggered when the link is visited.  - EVENT_ACTION_PASSWORD_VERIFY: Require visitors to enter a password before proceeding  - EVENT_ACTION_FORM_SUBMIT: Present a data collection form to visitors  - EVENT_ACTION_CONTACT_CARD: Generate a vCard (VCF) response with contact information  - EVENT_ACTION_MULTI_LINK: Present a multi-link page with multiple buttons for different destinations  - EVENT_ACTION_VISIT_TYPE_CONDITION: Route visitors based on whether it's a first or returning visit  - EVENT_ACTION_COUNTRY_CONDITION: Route visitors based on their country location  - EVENT_ACTION_DAY_OF_WEEK_CONDITION: Route visitors based on day of week  - EVENT_ACTION_TIME_OF_DAY_CONDITION: Route visitors based on time of day  - EVENT_ACTION_DAY_OF_MONTH_CONDITION: Route visitors based on day of month  - EVENT_ACTION_SPECIFIC_DATE_CONDITION: Route visitors based on specific calendar dates  - EVENT_ACTION_SOCIAL_LINKS_PAGE: Display a social links page (like Linktree)  - EVENT_ACTION_DEVICE_TYPE_CONDITION: Route visitors based on device type (e.g. MOBILE, DESKTOP, TABLET)  - EVENT_ACTION_DEVICE_PLATFORM_CONDITION: Route visitors based on device platform / operating system (e.g. iOS, Android, macOS)  - EVENT_ACTION_DEVICE_BROWSER_CONDITION: Route visitors based on browser family (e.g. Chrome, Safari, Firefox)  - EVENT_ACTION_DEVICE_BRAND_CONDITION: Route visitors based on hardware brand (e.g. Apple, Samsung, Google)  - EVENT_ACTION_DEVICE_ACTOR_CONDITION: Route visitors based on actor classification (e.g. HUMAN, BOT, AGENT)  - EVENT_ACTION_VISITOR_DATA_CONDITION: Route visitors based on their profile data or custom attributes
    #[serde(rename = "eventAction", skip_serializing_if = "Option::is_none")]
    pub event_action: Option<EventAction>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "payload", skip_serializing_if = "Option::is_none")]
    pub payload: Option<Box<models::WorkflowStepPayload>>,
}

impl WorkflowStepsServiceCreateBody {
    pub fn new() -> WorkflowStepsServiceCreateBody {
        WorkflowStepsServiceCreateBody {
            canvas_position: None,
            event_action: None,
            id: None,
            payload: None,
        }
    }
}
/// - EVENT_ACTION_UNSPECIFIED: Event action not specified  - EVENT_ACTION_CLIENT_REDIRECT: Redirect visitors to a destination URL  - EVENT_ACTION_LINK_VISIT: Entry step triggered when the link is visited.  - EVENT_ACTION_PASSWORD_VERIFY: Require visitors to enter a password before proceeding  - EVENT_ACTION_FORM_SUBMIT: Present a data collection form to visitors  - EVENT_ACTION_CONTACT_CARD: Generate a vCard (VCF) response with contact information  - EVENT_ACTION_MULTI_LINK: Present a multi-link page with multiple buttons for different destinations  - EVENT_ACTION_VISIT_TYPE_CONDITION: Route visitors based on whether it's a first or returning visit  - EVENT_ACTION_COUNTRY_CONDITION: Route visitors based on their country location  - EVENT_ACTION_DAY_OF_WEEK_CONDITION: Route visitors based on day of week  - EVENT_ACTION_TIME_OF_DAY_CONDITION: Route visitors based on time of day  - EVENT_ACTION_DAY_OF_MONTH_CONDITION: Route visitors based on day of month  - EVENT_ACTION_SPECIFIC_DATE_CONDITION: Route visitors based on specific calendar dates  - EVENT_ACTION_SOCIAL_LINKS_PAGE: Display a social links page (like Linktree)  - EVENT_ACTION_DEVICE_TYPE_CONDITION: Route visitors based on device type (e.g. MOBILE, DESKTOP, TABLET)  - EVENT_ACTION_DEVICE_PLATFORM_CONDITION: Route visitors based on device platform / operating system (e.g. iOS, Android, macOS)  - EVENT_ACTION_DEVICE_BROWSER_CONDITION: Route visitors based on browser family (e.g. Chrome, Safari, Firefox)  - EVENT_ACTION_DEVICE_BRAND_CONDITION: Route visitors based on hardware brand (e.g. Apple, Samsung, Google)  - EVENT_ACTION_DEVICE_ACTOR_CONDITION: Route visitors based on actor classification (e.g. HUMAN, BOT, AGENT)  - EVENT_ACTION_VISITOR_DATA_CONDITION: Route visitors based on their profile data or custom attributes
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EventAction {
    #[serde(rename = "EVENT_ACTION_UNSPECIFIED")]
    EventActionUnspecified,
    #[serde(rename = "EVENT_ACTION_CLIENT_REDIRECT")]
    EventActionClientRedirect,
    #[serde(rename = "EVENT_ACTION_LINK_VISIT")]
    EventActionLinkVisit,
    #[serde(rename = "EVENT_ACTION_PASSWORD_VERIFY")]
    EventActionPasswordVerify,
    #[serde(rename = "EVENT_ACTION_FORM_SUBMIT")]
    EventActionFormSubmit,
    #[serde(rename = "EVENT_ACTION_CONTACT_CARD")]
    EventActionContactCard,
    #[serde(rename = "EVENT_ACTION_MULTI_LINK")]
    EventActionMultiLink,
    #[serde(rename = "EVENT_ACTION_VISIT_TYPE_CONDITION")]
    EventActionVisitTypeCondition,
    #[serde(rename = "EVENT_ACTION_COUNTRY_CONDITION")]
    EventActionCountryCondition,
    #[serde(rename = "EVENT_ACTION_DAY_OF_WEEK_CONDITION")]
    EventActionDayOfWeekCondition,
    #[serde(rename = "EVENT_ACTION_TIME_OF_DAY_CONDITION")]
    EventActionTimeOfDayCondition,
    #[serde(rename = "EVENT_ACTION_DAY_OF_MONTH_CONDITION")]
    EventActionDayOfMonthCondition,
    #[serde(rename = "EVENT_ACTION_SPECIFIC_DATE_CONDITION")]
    EventActionSpecificDateCondition,
    #[serde(rename = "EVENT_ACTION_SOCIAL_LINKS_PAGE")]
    EventActionSocialLinksPage,
    #[serde(rename = "EVENT_ACTION_DEVICE_TYPE_CONDITION")]
    EventActionDeviceTypeCondition,
    #[serde(rename = "EVENT_ACTION_DEVICE_PLATFORM_CONDITION")]
    EventActionDevicePlatformCondition,
    #[serde(rename = "EVENT_ACTION_DEVICE_BROWSER_CONDITION")]
    EventActionDeviceBrowserCondition,
    #[serde(rename = "EVENT_ACTION_DEVICE_BRAND_CONDITION")]
    EventActionDeviceBrandCondition,
    #[serde(rename = "EVENT_ACTION_DEVICE_ACTOR_CONDITION")]
    EventActionDeviceActorCondition,
    #[serde(rename = "EVENT_ACTION_VISITOR_DATA_CONDITION")]
    EventActionVisitorDataCondition,
}

impl Default for EventAction {
    fn default() -> EventAction {
        Self::EventActionUnspecified
    }
}

