/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.13
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkspaceToken : Describes a long-lived credential Linkbreakers issues so back-end integrations can call workspace APIs without a human session, while keeping auditing metadata for security reviews.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkspaceToken {
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "createdBy", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "keyType", skip_serializing_if = "Option::is_none")]
    pub key_type: Option<models::WorkspaceTokenKeyType>,
    #[serde(rename = "lastUsedAt", skip_serializing_if = "Option::is_none")]
    pub last_used_at: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(rename = "workspaceId", skip_serializing_if = "Option::is_none")]
    pub workspace_id: Option<String>,
}

impl WorkspaceToken {
    /// Describes a long-lived credential Linkbreakers issues so back-end integrations can call workspace APIs without a human session, while keeping auditing metadata for security reviews.
    pub fn new() -> WorkspaceToken {
        WorkspaceToken {
            created_at: None,
            created_by: None,
            id: None,
            key_type: None,
            last_used_at: None,
            name: None,
            updated_at: None,
            workspace_id: None,
        }
    }
}

