/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkspaceInsight : Derived workspace usage insight that helps the UI pre-select the right link type when creating new links. Results are cached in Redis and refreshed on every successful link creation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkspaceInsight {
    #[serde(rename = "preferredLinkType", skip_serializing_if = "Option::is_none")]
    pub preferred_link_type: Option<models::PreferredLinkType>,
}

impl WorkspaceInsight {
    /// Derived workspace usage insight that helps the UI pre-select the right link type when creating new links. Results are cached in Redis and refreshed on every successful link creation.
    pub fn new() -> WorkspaceInsight {
        WorkspaceInsight {
            preferred_link_type: None,
        }
    }
}

