/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.43.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowStepPayload {
    #[serde(rename = "clientRedirect", skip_serializing_if = "Option::is_none")]
    pub client_redirect: Option<Box<models::ClientRedirectPayload>>,
    #[serde(rename = "countryCondition", skip_serializing_if = "Option::is_none")]
    pub country_condition: Option<Box<models::CountryConditionPayload>>,
    #[serde(rename = "dayOfMonthCondition", skip_serializing_if = "Option::is_none")]
    pub day_of_month_condition: Option<Box<models::DayOfMonthConditionPayload>>,
    #[serde(rename = "dayOfWeekCondition", skip_serializing_if = "Option::is_none")]
    pub day_of_week_condition: Option<Box<models::DayOfWeekConditionPayload>>,
    #[serde(rename = "deviceActorCondition", skip_serializing_if = "Option::is_none")]
    pub device_actor_condition: Option<Box<models::DeviceActorConditionPayload>>,
    #[serde(rename = "deviceBrandCondition", skip_serializing_if = "Option::is_none")]
    pub device_brand_condition: Option<Box<models::DeviceBrandConditionPayload>>,
    #[serde(rename = "deviceBrowserCondition", skip_serializing_if = "Option::is_none")]
    pub device_browser_condition: Option<Box<models::DeviceBrowserConditionPayload>>,
    #[serde(rename = "devicePlatformCondition", skip_serializing_if = "Option::is_none")]
    pub device_platform_condition: Option<Box<models::DevicePlatformConditionPayload>>,
    #[serde(rename = "deviceTypeCondition", skip_serializing_if = "Option::is_none")]
    pub device_type_condition: Option<Box<models::DeviceTypeConditionPayload>>,
    #[serde(rename = "form", skip_serializing_if = "Option::is_none")]
    pub form: Option<Box<models::FormPayload>>,
    /// Reserved for future link visit specific configuration
    #[serde(rename = "linkVisit", skip_serializing_if = "Option::is_none")]
    pub link_visit: Option<serde_json::Value>,
    #[serde(rename = "multiLink", skip_serializing_if = "Option::is_none")]
    pub multi_link: Option<Box<models::MultiLinkPayload>>,
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<Box<models::PasswordPayload>>,
    #[serde(rename = "socialLinks", skip_serializing_if = "Option::is_none")]
    pub social_links: Option<Box<models::SocialLinksPayload>>,
    #[serde(rename = "specificDateCondition", skip_serializing_if = "Option::is_none")]
    pub specific_date_condition: Option<Box<models::SpecificDateConditionPayload>>,
    #[serde(rename = "timeOfDayCondition", skip_serializing_if = "Option::is_none")]
    pub time_of_day_condition: Option<Box<models::TimeOfDayConditionPayload>>,
    #[serde(rename = "vcard", skip_serializing_if = "Option::is_none")]
    pub vcard: Option<Box<models::VCardPayload>>,
    #[serde(rename = "visitTypeCondition", skip_serializing_if = "Option::is_none")]
    pub visit_type_condition: Option<Box<models::VisitTypeConditionPayload>>,
}

impl WorkflowStepPayload {
    pub fn new() -> WorkflowStepPayload {
        WorkflowStepPayload {
            client_redirect: None,
            country_condition: None,
            day_of_month_condition: None,
            day_of_week_condition: None,
            device_actor_condition: None,
            device_brand_condition: None,
            device_browser_condition: None,
            device_platform_condition: None,
            device_type_condition: None,
            form: None,
            link_visit: None,
            multi_link: None,
            password: None,
            social_links: None,
            specific_date_condition: None,
            time_of_day_condition: None,
            vcard: None,
            visit_type_condition: None,
        }
    }
}

