/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.44.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkspaceMetric : Snapshot of high-level counters Linkbreakers surfaces on the dashboard so teams can track workspace growth at a glance.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkspaceMetric {
    #[serde(rename = "tokenCreditsLimit", skip_serializing_if = "Option::is_none")]
    pub token_credits_limit: Option<i32>,
    #[serde(rename = "tokenCreditsUsed", skip_serializing_if = "Option::is_none")]
    pub token_credits_used: Option<i32>,
    #[serde(rename = "totalDirectories", skip_serializing_if = "Option::is_none")]
    pub total_directories: Option<i32>,
    #[serde(rename = "totalEvents", skip_serializing_if = "Option::is_none")]
    pub total_events: Option<i32>,
    #[serde(rename = "totalLinks", skip_serializing_if = "Option::is_none")]
    pub total_links: Option<i32>,
    #[serde(rename = "totalMembers", skip_serializing_if = "Option::is_none")]
    pub total_members: Option<i32>,
    #[serde(rename = "totalMonthlyEvents", skip_serializing_if = "Option::is_none")]
    pub total_monthly_events: Option<i32>,
    #[serde(rename = "totalQrcodeTemplates", skip_serializing_if = "Option::is_none")]
    pub total_qrcode_templates: Option<i32>,
}

impl WorkspaceMetric {
    /// Snapshot of high-level counters Linkbreakers surfaces on the dashboard so teams can track workspace growth at a glance.
    pub fn new() -> WorkspaceMetric {
        WorkspaceMetric {
            token_credits_limit: None,
            token_credits_used: None,
            total_directories: None,
            total_events: None,
            total_links: None,
            total_members: None,
            total_monthly_events: None,
            total_qrcode_templates: None,
        }
    }
}

