/*
 * Linkbreakers API
 *
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.9
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkflowStepNodeType : Node types define how workflow steps manage their outbound connections:  COMPOSITE nodes manage their own exit paths through their payload structure. They have multiple possible next steps defined within the payload itself: - Forms: Can have skip and submit paths - Multi-links: Each button has its own next_step_id - Conditions: Each condition outcome routes to a different next_step_id  ATOMIC nodes are simple steps with a single, direct connection to the next step. They use the standard parent-child relationship mechanism.  Connection Rules: - ✅ Connections TO any node type are allowed - ✅ Connections FROM atomic nodes are allowed - ❌ Direct connections FROM composite nodes are NOT allowed   (They manage routing through their payload instead)  Example: A multi-link node with 3 buttons defines 3 possible next steps in its payload.buttons[].next_step_id fields, not through direct parent-child relationships.   - NODE_TYPE_UNSPECIFIED: Workflow step node type not specified  - NODE_TYPE_COMPOSITE: Composite nodes manage multiple exit paths through their payload structure. Examples: FORM_SUBMIT, MULTI_LINK, VISIT_TYPE_CONDITION, COUNTRY_CONDITION, DAY_OF_WEEK_CONDITION, TIME_OF_DAY_CONDITION, DAY_OF_MONTH_CONDITION, SPECIFIC_DATE_CONDITION  Connection behavior: Cannot create direct parent-child connections FROM these nodes. They define their next steps within the payload (e.g., button.next_step_id, option.next_step_id).  - NODE_TYPE_ATOMIC: Atomic nodes are simple steps with no internal routing logic. Examples: LINK_VISIT, CLIENT_REDIRECT, PASSWORD_VERIFY, CONTACT_CARD  Connection behavior: Can create standard parent-child connections to any other node.
/// Node types define how workflow steps manage their outbound connections:  COMPOSITE nodes manage their own exit paths through their payload structure. They have multiple possible next steps defined within the payload itself: - Forms: Can have skip and submit paths - Multi-links: Each button has its own next_step_id - Conditions: Each condition outcome routes to a different next_step_id  ATOMIC nodes are simple steps with a single, direct connection to the next step. They use the standard parent-child relationship mechanism.  Connection Rules: - ✅ Connections TO any node type are allowed - ✅ Connections FROM atomic nodes are allowed - ❌ Direct connections FROM composite nodes are NOT allowed   (They manage routing through their payload instead)  Example: A multi-link node with 3 buttons defines 3 possible next steps in its payload.buttons[].next_step_id fields, not through direct parent-child relationships.   - NODE_TYPE_UNSPECIFIED: Workflow step node type not specified  - NODE_TYPE_COMPOSITE: Composite nodes manage multiple exit paths through their payload structure. Examples: FORM_SUBMIT, MULTI_LINK, VISIT_TYPE_CONDITION, COUNTRY_CONDITION, DAY_OF_WEEK_CONDITION, TIME_OF_DAY_CONDITION, DAY_OF_MONTH_CONDITION, SPECIFIC_DATE_CONDITION  Connection behavior: Cannot create direct parent-child connections FROM these nodes. They define their next steps within the payload (e.g., button.next_step_id, option.next_step_id).  - NODE_TYPE_ATOMIC: Atomic nodes are simple steps with no internal routing logic. Examples: LINK_VISIT, CLIENT_REDIRECT, PASSWORD_VERIFY, CONTACT_CARD  Connection behavior: Can create standard parent-child connections to any other node.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WorkflowStepNodeType {
    #[serde(rename = "NODE_TYPE_UNSPECIFIED")]
    NodeTypeUnspecified,
    #[serde(rename = "NODE_TYPE_COMPOSITE")]
    NodeTypeComposite,
    #[serde(rename = "NODE_TYPE_ATOMIC")]
    NodeTypeAtomic,

}

impl std::fmt::Display for WorkflowStepNodeType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::NodeTypeUnspecified => write!(f, "NODE_TYPE_UNSPECIFIED"),
            Self::NodeTypeComposite => write!(f, "NODE_TYPE_COMPOSITE"),
            Self::NodeTypeAtomic => write!(f, "NODE_TYPE_ATOMIC"),
        }
    }
}

impl Default for WorkflowStepNodeType {
    fn default() -> WorkflowStepNodeType {
        Self::NodeTypeUnspecified
    }
}

